package edu.cuit.module.auchc.entity;

// Generated 2015-4-14 19:14:43 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Prictureinfomation generated by hbm2java
 */
public class Prictureinfomation implements java.io.Serializable {

	private String pictureCode;
	private String approveDataCode;
	private String proctureUrl;
	private Date collectionTime;
	private String remark;
	private String dataOrigin;
	private String cropGrowthPeriod;

	public Prictureinfomation() {
	}

	public Prictureinfomation(String pictureCode, String approveDataCode) {
		this.pictureCode = pictureCode;
		this.approveDataCode = approveDataCode;
	}

	public Prictureinfomation(String pictureCode, String approveDataCode,
			String proctureUrl, Date collectionTime, String remark,
			String dataOrigin) {
		this.pictureCode = pictureCode;
		this.approveDataCode = approveDataCode;
		this.proctureUrl = proctureUrl;
		this.collectionTime = collectionTime;
		this.remark = remark;
		this.dataOrigin = dataOrigin;
	}

	public String getPictureCode() {
		return this.pictureCode;
	}

	public void setPictureCode(String pictureCode) {
		this.pictureCode = pictureCode;
	}

	public String getApproveDataCode() {
		return this.approveDataCode;
	}

	public void setApproveDataCode(String approveDataCode) {
		this.approveDataCode = approveDataCode;
	}

	public String getProctureUrl() {
		return this.proctureUrl;
	}

	public void setProctureUrl(String proctureUrl) {
		this.proctureUrl = proctureUrl;
	}

	public Date getCollectionTime() {
		return this.collectionTime;
	}

	public void setCollectionTime(Date collectionTime) {
		this.collectionTime = collectionTime;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getDataOrigin() {
		return this.dataOrigin;
	}

	public void setDataOrigin(String dataOrigin) {
		this.dataOrigin = dataOrigin;
	}

	public String getCropGrowthPeriod() {
		return cropGrowthPeriod;
	}

	public void setCropGrowthPeriod(String cropGrowthPeriod) {
		this.cropGrowthPeriod = cropGrowthPeriod;
	}

}
