package edu.cuit.module.sys.entity;

// Generated 2015-4-13 16:59:09 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * TbcuitmoonInformation generated by hbm2java
 */
public class TbcuitmoonInformation implements java.io.Serializable {

	private String cuitMoonInformationId;
	private String cuitMoonInformationContent;
	private String cuitMoonInformationFrom;
	private String cuitMoonInformationTo;
	private Date cuitMoonInformationSendTime;
	private Long cuitMoonInformationStatus;

	public TbcuitmoonInformation() {
	}

	public TbcuitmoonInformation(String cuitMoonInformationId) {
		this.cuitMoonInformationId = cuitMoonInformationId;
	}

	public TbcuitmoonInformation(String cuitMoonInformationId,
			String cuitMoonInformationContent, String cuitMoonInformationFrom,
			String cuitMoonInformationTo, Date cuitMoonInformationSendTime,
			Long cuitMoonInformationStatus) {
		this.cuitMoonInformationId = cuitMoonInformationId;
		this.cuitMoonInformationContent = cuitMoonInformationContent;
		this.cuitMoonInformationFrom = cuitMoonInformationFrom;
		this.cuitMoonInformationTo = cuitMoonInformationTo;
		this.cuitMoonInformationSendTime = cuitMoonInformationSendTime;
		this.cuitMoonInformationStatus = cuitMoonInformationStatus;
	}

	public String getCuitMoonInformationId() {
		return this.cuitMoonInformationId;
	}

	public void setCuitMoonInformationId(String cuitMoonInformationId) {
		this.cuitMoonInformationId = cuitMoonInformationId;
	}

	public String getCuitMoonInformationContent() {
		return this.cuitMoonInformationContent;
	}

	public void setCuitMoonInformationContent(String cuitMoonInformationContent) {
		this.cuitMoonInformationContent = cuitMoonInformationContent;
	}

	public String getCuitMoonInformationFrom() {
		return this.cuitMoonInformationFrom;
	}

	public void setCuitMoonInformationFrom(String cuitMoonInformationFrom) {
		this.cuitMoonInformationFrom = cuitMoonInformationFrom;
	}

	public String getCuitMoonInformationTo() {
		return this.cuitMoonInformationTo;
	}

	public void setCuitMoonInformationTo(String cuitMoonInformationTo) {
		this.cuitMoonInformationTo = cuitMoonInformationTo;
	}

	public Date getCuitMoonInformationSendTime() {
		return this.cuitMoonInformationSendTime;
	}

	public void setCuitMoonInformationSendTime(Date cuitMoonInformationSendTime) {
		this.cuitMoonInformationSendTime = cuitMoonInformationSendTime;
	}

	public Long getCuitMoonInformationStatus() {
		return this.cuitMoonInformationStatus;
	}

	public void setCuitMoonInformationStatus(Long cuitMoonInformationStatus) {
		this.cuitMoonInformationStatus = cuitMoonInformationStatus;
	}

}
