package edu.cuit.module.entm.entity;

// Generated 2015-4-14 18:33:50 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * TbncpQiyeNews generated by hbm2java
 */
public class TbncpQiyeNews implements java.io.Serializable {

	private String newsId;
	private Date cretime;
	private String newstitle;
	private String newscontent;
	private String qiyenum;

	public TbncpQiyeNews() {
	}

	public TbncpQiyeNews(String newsId) {
		this.newsId = newsId;
	}

	public TbncpQiyeNews(String newsId, Date cretime, String newstitle,
			String newscontent, String qiyenum) {
		this.newsId = newsId;
		this.cretime = cretime;
		this.newstitle = newstitle;
		this.newscontent = newscontent;
		this.qiyenum = qiyenum;
	}

	public String getNewsId() {
		return this.newsId;
	}

	public void setNewsId(String newsId) {
		this.newsId = newsId;
	}

	public Date getCretime() {
		return this.cretime;
	}

	public void setCretime(Date cretime) {
		this.cretime = cretime;
	}

	public String getNewstitle() {
		return this.newstitle;
	}

	public void setNewstitle(String newstitle) {
		this.newstitle = newstitle;
	}

	public String getNewscontent() {
		return this.newscontent;
	}

	public void setNewscontent(String newscontent) {
		this.newscontent = newscontent;
	}

	public String getQiyenum() {
		return this.qiyenum;
	}

	public void setQiyenum(String qiyenum) {
		this.qiyenum = qiyenum;
	}

}
