package edu.cuit.module.sys.entity;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.List;

import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.NotBlank;

// Generated 2015-4-13 16:59:09 by Hibernate Tools 4.3.1

/**
 * TbcuitmoonDictionary generated by hbm2java
 */
public class TbcuitmoonDictionary implements java.io.Serializable {

	private String cuitMoonDictionaryId;
	@NotBlank(message="不能为空")
	private String cuitMoonDictionaryName;
	@NotNull(message="不能为空")
	private Long cuitMoonDictionaryCode;
	private Long cuitMoonParentDictionaryCode;
	private Integer cuitMoonDictionaryOrderNum = 1;
	private String cuitMoonDictionaryRemarks;
	
	private boolean hasChild;
	private List<?> childDics = Collections.emptyList();

	public TbcuitmoonDictionary() {
	}

	public TbcuitmoonDictionary(String cuitMoonDictionaryId,
			String cuitMoonDictionaryName, Long cuitMoonDictionaryCode) {
		this.cuitMoonDictionaryId = cuitMoonDictionaryId;
		this.cuitMoonDictionaryName = cuitMoonDictionaryName;
		this.cuitMoonDictionaryCode = cuitMoonDictionaryCode;
	}

	public TbcuitmoonDictionary(String cuitMoonDictionaryId,
			String cuitMoonDictionaryName, Long cuitMoonDictionaryCode,
			Long cuitMoonParentDictionaryCode,
			Integer cuitMoonDictionaryOrderNum, String cuitMoonDictionaryRemarks) {
		this.cuitMoonDictionaryId = cuitMoonDictionaryId;
		this.cuitMoonDictionaryName = cuitMoonDictionaryName;
		this.cuitMoonDictionaryCode = cuitMoonDictionaryCode;
		this.cuitMoonParentDictionaryCode = cuitMoonParentDictionaryCode;
		this.cuitMoonDictionaryOrderNum = cuitMoonDictionaryOrderNum;
		this.cuitMoonDictionaryRemarks = cuitMoonDictionaryRemarks;
	}

	public String getCuitMoonDictionaryId() {
		return this.cuitMoonDictionaryId;
	}

	public void setCuitMoonDictionaryId(String cuitMoonDictionaryId) {
		this.cuitMoonDictionaryId = cuitMoonDictionaryId;
	}

	public String getCuitMoonDictionaryName() {
		return this.cuitMoonDictionaryName;
	}

	public void setCuitMoonDictionaryName(String cuitMoonDictionaryName) {
		this.cuitMoonDictionaryName = cuitMoonDictionaryName;
	}

	public Long getCuitMoonDictionaryCode() {
		return this.cuitMoonDictionaryCode;
	}

	public void setCuitMoonDictionaryCode(Long cuitMoonDictionaryCode) {
		this.cuitMoonDictionaryCode = cuitMoonDictionaryCode;
	}

	public Long getCuitMoonParentDictionaryCode() {
		return this.cuitMoonParentDictionaryCode;
	}

	public void setCuitMoonParentDictionaryCode(
			Long cuitMoonParentDictionaryCode) {
		this.cuitMoonParentDictionaryCode = cuitMoonParentDictionaryCode;
	}

	public Integer getCuitMoonDictionaryOrderNum() {
		return this.cuitMoonDictionaryOrderNum;
	}

	public void setCuitMoonDictionaryOrderNum(Integer cuitMoonDictionaryOrderNum) {
		this.cuitMoonDictionaryOrderNum = cuitMoonDictionaryOrderNum;
	}

	public String getCuitMoonDictionaryRemarks() {
		return this.cuitMoonDictionaryRemarks;
	}

	public void setCuitMoonDictionaryRemarks(String cuitMoonDictionaryRemarks) {
		this.cuitMoonDictionaryRemarks = cuitMoonDictionaryRemarks;
	}

	/**
	 * @return the hasChild
	 */
	public boolean isHasChild() {
		return hasChild;
	}

	/**
	 * @param hasChild the hasChild to set
	 */
	public void setHasChild(boolean hasChild) {
		this.hasChild = hasChild;
	}

	/**
	 * @return the childDics
	 */
	public List<?> getChildDics() {
		return childDics;
	}

	/**
	 * @param childDics the childDics to set
	 */
	public void setChildDics(List<?> childDics) {
		this.childDics = childDics;
	}

}
