package edu.cuit.module.sys.entity;

import java.util.HashSet;
import java.util.Set;

import org.hibernate.validator.constraints.NotBlank;

// Generated 2015-4-13 16:59:09 by Hibernate Tools 4.3.1

/**
 * TbcuitmoonJurisdiction generated by hbm2java
 */
public class TbcuitmoonJurisdiction implements java.io.Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 4825371727655033073L;
	private String cuitMoonJurisdictionId;
	@NotBlank(message="名称不能为空")
	private String cuitMoonJurisdictionName;
	@NotBlank(message="权限代码不能为空")
	private String cuitMoonJurisdictionCode;
	private String cuitMoonModuleId;
	private Long cuitMoonJurisdictionStatus;
	private Integer cuitMoonJurisdictionOrderNum;
	private String cuitMoonJurisdictionDescription;
	private String cuitMoonJurisdictionRemarks;
	private Set<TbcuitmoonRole> tbcuitmoonRoles = new HashSet<TbcuitmoonRole>();

	public TbcuitmoonJurisdiction() {
	}

	public TbcuitmoonJurisdiction(String cuitMoonJurisdictionId,
			String cuitMoonJurisdictionName, String cuitMoonJurisdictionCode,
			String cuitMoonModuleId) {
		this.cuitMoonJurisdictionId = cuitMoonJurisdictionId;
		this.cuitMoonJurisdictionName = cuitMoonJurisdictionName;
		this.cuitMoonJurisdictionCode = cuitMoonJurisdictionCode;
		this.cuitMoonModuleId = cuitMoonModuleId;
	}

	public TbcuitmoonJurisdiction(String cuitMoonJurisdictionId,
			String cuitMoonJurisdictionName, String cuitMoonJurisdictionCode,
			String cuitMoonModuleId, Long cuitMoonJurisdictionStatus,
			Integer cuitMoonJurisdictionOrderNum,
			String cuitMoonJurisdictionDescription,
			String cuitMoonJurisdictionRemarks) {
		this.cuitMoonJurisdictionId = cuitMoonJurisdictionId;
		this.cuitMoonJurisdictionName = cuitMoonJurisdictionName;
		this.cuitMoonJurisdictionCode = cuitMoonJurisdictionCode;
		this.cuitMoonModuleId = cuitMoonModuleId;
		this.cuitMoonJurisdictionStatus = cuitMoonJurisdictionStatus;
		this.cuitMoonJurisdictionOrderNum = cuitMoonJurisdictionOrderNum;
		this.cuitMoonJurisdictionDescription = cuitMoonJurisdictionDescription;
		this.cuitMoonJurisdictionRemarks = cuitMoonJurisdictionRemarks;
	}

	public String getCuitMoonJurisdictionId() {
		return this.cuitMoonJurisdictionId;
	}

	public void setCuitMoonJurisdictionId(String cuitMoonJurisdictionId) {
		this.cuitMoonJurisdictionId = cuitMoonJurisdictionId;
	}

	public String getCuitMoonJurisdictionName() {
		return this.cuitMoonJurisdictionName;
	}

	public void setCuitMoonJurisdictionName(String cuitMoonJurisdictionName) {
		this.cuitMoonJurisdictionName = cuitMoonJurisdictionName;
	}

	public String getCuitMoonJurisdictionCode() {
		return this.cuitMoonJurisdictionCode;
	}

	public void setCuitMoonJurisdictionCode(String cuitMoonJurisdictionCode) {
		this.cuitMoonJurisdictionCode = cuitMoonJurisdictionCode;
	}

	public String getCuitMoonModuleId() {
		return this.cuitMoonModuleId;
	}

	public void setCuitMoonModuleId(String cuitMoonModuleId) {
		this.cuitMoonModuleId = cuitMoonModuleId;
	}

	public Long getCuitMoonJurisdictionStatus() {
		return this.cuitMoonJurisdictionStatus;
	}

	public void setCuitMoonJurisdictionStatus(Long cuitMoonJurisdictionStatus) {
		this.cuitMoonJurisdictionStatus = cuitMoonJurisdictionStatus;
	}

	public Integer getCuitMoonJurisdictionOrderNum() {
		return this.cuitMoonJurisdictionOrderNum;
	}

	public void setCuitMoonJurisdictionOrderNum(
			Integer cuitMoonJurisdictionOrderNum) {
		this.cuitMoonJurisdictionOrderNum = cuitMoonJurisdictionOrderNum;
	}

	public String getCuitMoonJurisdictionDescription() {
		return this.cuitMoonJurisdictionDescription;
	}

	public void setCuitMoonJurisdictionDescription(
			String cuitMoonJurisdictionDescription) {
		this.cuitMoonJurisdictionDescription = cuitMoonJurisdictionDescription;
	}

	public String getCuitMoonJurisdictionRemarks() {
		return this.cuitMoonJurisdictionRemarks;
	}

	public void setCuitMoonJurisdictionRemarks(
			String cuitMoonJurisdictionRemarks) {
		this.cuitMoonJurisdictionRemarks = cuitMoonJurisdictionRemarks;
	}

	/**
	 * @return the tbcuitmoonRoles
	 */
	public Set<TbcuitmoonRole> getTbcuitmoonRoles() {
		return tbcuitmoonRoles;
	}

	/**
	 * @param tbcuitmoonRoles the tbcuitmoonRoles to set
	 */
	public void setTbcuitmoonRoles(Set<TbcuitmoonRole> tbcuitmoonRoles) {
		this.tbcuitmoonRoles = tbcuitmoonRoles;
	}

}
