package edu.cuit.module.sys.entity;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.NotBlank;

// Generated 2015-4-13 16:59:09 by Hibernate Tools 4.3.1

/**
 * TbcuitmoonArea generated by hbm2java
 */
public class TbcuitmoonArea implements java.io.Serializable {

	private String cuitMoonAreaId;
	private String cuitMoonAreaName;
	private long cuitMoonAreaCode;
	private long cuitMoonParentAreaCode;
	private Integer cuitMoonAreaOrderNum = 1;
	private String cuitMoonAreaRemarks;
	private List<?> childAreas = new ArrayList<>();

	public TbcuitmoonArea() {
	}

	public TbcuitmoonArea(String cuitMoonAreaId, String cuitMoonAreaName,
			long cuitMoonAreaCode) {
		this.cuitMoonAreaId = cuitMoonAreaId;
		this.cuitMoonAreaName = cuitMoonAreaName;
		this.cuitMoonAreaCode = cuitMoonAreaCode;
	}

	public TbcuitmoonArea(String cuitMoonAreaId, String cuitMoonAreaName,
			long cuitMoonAreaCode, Long cuitMoonParentAreaCode,
			Integer cuitMoonAreaOrderNum, String cuitMoonAreaRemarks) {
		this.cuitMoonAreaId = cuitMoonAreaId;
		this.cuitMoonAreaName = cuitMoonAreaName;
		this.cuitMoonAreaCode = cuitMoonAreaCode;
		this.cuitMoonParentAreaCode = cuitMoonParentAreaCode;
		this.cuitMoonAreaOrderNum = cuitMoonAreaOrderNum;
		this.cuitMoonAreaRemarks = cuitMoonAreaRemarks;
	}

	public String getCuitMoonAreaId() {
		return this.cuitMoonAreaId;
	}

	public void setCuitMoonAreaId(String cuitMoonAreaId) {
		this.cuitMoonAreaId = cuitMoonAreaId;
	}

	public String getCuitMoonAreaName() {
		return this.cuitMoonAreaName;
	}

	public void setCuitMoonAreaName(String cuitMoonAreaName) {
		this.cuitMoonAreaName = cuitMoonAreaName;
	}

	public long getCuitMoonAreaCode() {
		return this.cuitMoonAreaCode;
	}

	public void setCuitMoonAreaCode(long cuitMoonAreaCode) {
		this.cuitMoonAreaCode = cuitMoonAreaCode;
	}

	public Long getCuitMoonParentAreaCode() {
		return this.cuitMoonParentAreaCode;
	}

	public void setCuitMoonParentAreaCode(Long cuitMoonParentAreaCode) {
		this.cuitMoonParentAreaCode = cuitMoonParentAreaCode;
	}

	public Integer getCuitMoonAreaOrderNum() {
		return this.cuitMoonAreaOrderNum;
	}

	public void setCuitMoonAreaOrderNum(Integer cuitMoonAreaOrderNum) {
		this.cuitMoonAreaOrderNum = cuitMoonAreaOrderNum;
	}

	public String getCuitMoonAreaRemarks() {
		return this.cuitMoonAreaRemarks;
	}

	public void setCuitMoonAreaRemarks(String cuitMoonAreaRemarks) {
		this.cuitMoonAreaRemarks = cuitMoonAreaRemarks;
	}

	/**
	 * @return the childAreas
	 */
	public List<?> getChildAreas() {
		return childAreas;
	}

	/**
	 * @param childAreas
	 *            the childAreas to set
	 */
	public void setChildAreas(List<?> childAreas) {
		this.childAreas = childAreas;
	}

}
