package edu.cuit.module.sys.entity;
 
// Generated 2015-4-13 16:59:09 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.hibernate.validator.constraints.NotBlank;

/**
 * TbcuitmoonUser generated by hbm2java
 */
public class TbcuitmoonUser implements java.io.Serializable {
	
	private String cuitMoonUserId;
	private String cuitMoonUserName;
	private String cuitMoonUserPassWord;
	private String cuitMoonUserRealName;
	private Long cuitMoonUserSex;
	private Date cuitMoonUserBirthday;
	private String cuitMoonUserCellphone;
	private String cuitMoonUserAddress;
	private String cuitMoonUserZipCode;
	private String cuitMoonUserEmail;
	private String cuitMoonUserQq;
	private String cuitMoonUserMsn;
	private Date cuitMoonUserRegTime;
	private Long cuitMoonUserLoginCount;
	private Long cuitMoonUserStatus;
	private String cuitMoonUserRemarks;
	private String cuitMoonAreaId;
	private String cuitMoonDepartmentId="0";
	private Long cuitMoonUserLoginStatus;
	private Set<TbcuitmoonRole> tbcuitmoonRoles = new HashSet<TbcuitmoonRole>();

	public TbcuitmoonUser() {
	}

	public TbcuitmoonUser(String cuitMoonUserId, String cuitMoonUserName,
			String cuitMoonUserPassWord, String cuitMoonAreaId,
			String cuitMoonDepartmentId) {
		this.cuitMoonUserId = cuitMoonUserId;
		this.cuitMoonUserName = cuitMoonUserName;
		this.cuitMoonUserPassWord = cuitMoonUserPassWord;
		this.cuitMoonAreaId = cuitMoonAreaId;
		this.cuitMoonDepartmentId = cuitMoonDepartmentId;
	}

	public TbcuitmoonUser(String cuitMoonUserId, String cuitMoonUserName,
			String cuitMoonUserPassWord, String cuitMoonUserRealName,
			Long cuitMoonUserSex, Date cuitMoonUserBirthday,
			String cuitMoonUserCellphone, String cuitMoonUserAddress,
			String cuitMoonUserZipCode, String cuitMoonUserEmail,
			String cuitMoonUserQq, String cuitMoonUserMsn,
			Date cuitMoonUserRegTime, Long cuitMoonUserLoginCount,
			Long cuitMoonUserStatus, String cuitMoonUserRemarks,
			String cuitMoonAreaId, String cuitMoonDepartmentId,
			Long cuitMoonUserLoginStatus) {
		this.cuitMoonUserId = cuitMoonUserId;
		this.cuitMoonUserName = cuitMoonUserName;
		this.cuitMoonUserPassWord = cuitMoonUserPassWord;
		this.cuitMoonUserRealName = cuitMoonUserRealName;
		this.cuitMoonUserSex = cuitMoonUserSex;
		this.cuitMoonUserBirthday = cuitMoonUserBirthday;
		this.cuitMoonUserCellphone = cuitMoonUserCellphone;
		this.cuitMoonUserAddress = cuitMoonUserAddress;
		this.cuitMoonUserZipCode = cuitMoonUserZipCode;
		this.cuitMoonUserEmail = cuitMoonUserEmail;
		this.cuitMoonUserQq = cuitMoonUserQq;
		this.cuitMoonUserMsn = cuitMoonUserMsn;
		this.cuitMoonUserRegTime = cuitMoonUserRegTime;
		this.cuitMoonUserLoginCount = cuitMoonUserLoginCount;
		this.cuitMoonUserStatus = cuitMoonUserStatus;
		this.cuitMoonUserRemarks = cuitMoonUserRemarks;
		this.cuitMoonAreaId = cuitMoonAreaId;
		this.cuitMoonDepartmentId = cuitMoonDepartmentId;
		this.cuitMoonUserLoginStatus = cuitMoonUserLoginStatus;
	}

	public String getCuitMoonUserId() {
		return this.cuitMoonUserId;
	}

	public void setCuitMoonUserId(String cuitMoonUserId) {
		this.cuitMoonUserId = cuitMoonUserId;
	}

	public String getCuitMoonUserName() {
		return this.cuitMoonUserName;
	}

	public void setCuitMoonUserName(String cuitMoonUserName) {
		this.cuitMoonUserName = cuitMoonUserName;
	}

	public String getCuitMoonUserPassWord() {
		return this.cuitMoonUserPassWord;
	}

	public void setCuitMoonUserPassWord(String cuitMoonUserPassWord) {
		this.cuitMoonUserPassWord = cuitMoonUserPassWord;
	}

	public String getCuitMoonUserRealName() {
		return this.cuitMoonUserRealName;
	}

	public void setCuitMoonUserRealName(String cuitMoonUserRealName) {
		this.cuitMoonUserRealName = cuitMoonUserRealName;
	}

	public Long getCuitMoonUserSex() {
		return this.cuitMoonUserSex;
	}

	public void setCuitMoonUserSex(Long cuitMoonUserSex) {
		this.cuitMoonUserSex = cuitMoonUserSex;
	}

	public Date getCuitMoonUserBirthday() {
		return this.cuitMoonUserBirthday;
	}

	public void setCuitMoonUserBirthday(Date cuitMoonUserBirthday) {
		this.cuitMoonUserBirthday = cuitMoonUserBirthday;
	}

	public String getCuitMoonUserCellphone() {
		return this.cuitMoonUserCellphone;
	}

	public void setCuitMoonUserCellphone(String cuitMoonUserCellphone) {
		this.cuitMoonUserCellphone = cuitMoonUserCellphone;
	}

	public String getCuitMoonUserAddress() {
		return this.cuitMoonUserAddress;
	}

	public void setCuitMoonUserAddress(String cuitMoonUserAddress) {
		this.cuitMoonUserAddress = cuitMoonUserAddress;
	}

	public String getCuitMoonUserZipCode() {
		return this.cuitMoonUserZipCode;
	}

	public void setCuitMoonUserZipCode(String cuitMoonUserZipCode) {
		this.cuitMoonUserZipCode = cuitMoonUserZipCode;
	}

	public String getCuitMoonUserEmail() {
		return this.cuitMoonUserEmail;
	}

	public void setCuitMoonUserEmail(String cuitMoonUserEmail) {
		this.cuitMoonUserEmail = cuitMoonUserEmail;
	}

	public String getCuitMoonUserQq() {
		return this.cuitMoonUserQq;
	}

	public void setCuitMoonUserQq(String cuitMoonUserQq) {
		this.cuitMoonUserQq = cuitMoonUserQq;
	}

	public String getCuitMoonUserMsn() {
		return this.cuitMoonUserMsn;
	}

	public void setCuitMoonUserMsn(String cuitMoonUserMsn) {
		this.cuitMoonUserMsn = cuitMoonUserMsn;
	}

	public Date getCuitMoonUserRegTime() {
		return this.cuitMoonUserRegTime;
	}

	public void setCuitMoonUserRegTime(Date cuitMoonUserRegTime) {
		this.cuitMoonUserRegTime = cuitMoonUserRegTime;
	}

	public Long getCuitMoonUserLoginCount() {
		return this.cuitMoonUserLoginCount;
	}

	public void setCuitMoonUserLoginCount(Long cuitMoonUserLoginCount) {
		this.cuitMoonUserLoginCount = cuitMoonUserLoginCount;
	}

	public Long getCuitMoonUserStatus() {
		return this.cuitMoonUserStatus;
	}

	public void setCuitMoonUserStatus(Long cuitMoonUserStatus) {
		this.cuitMoonUserStatus = cuitMoonUserStatus;
	}

	public String getCuitMoonUserRemarks() {
		return this.cuitMoonUserRemarks;
	}

	public void setCuitMoonUserRemarks(String cuitMoonUserRemarks) {
		this.cuitMoonUserRemarks = cuitMoonUserRemarks;
	}

	public String getCuitMoonAreaId() {
		return this.cuitMoonAreaId;
	}

	public void setCuitMoonAreaId(String cuitMoonAreaId) {
		this.cuitMoonAreaId = cuitMoonAreaId;
	}

	public String getCuitMoonDepartmentId() {
		return this.cuitMoonDepartmentId;
	}

	public void setCuitMoonDepartmentId(String cuitMoonDepartmentId) {
		this.cuitMoonDepartmentId = cuitMoonDepartmentId;
	}

	public Long getCuitMoonUserLoginStatus() {
		return this.cuitMoonUserLoginStatus;
	}

	public void setCuitMoonUserLoginStatus(Long cuitMoonUserLoginStatus) {
		this.cuitMoonUserLoginStatus = cuitMoonUserLoginStatus;
	}

	/**
	 * @return the tbcuitmoonRoles
	 */
	public Set<TbcuitmoonRole> getTbcuitmoonRoles() {
		return tbcuitmoonRoles;
	}

	/**
	 * @param tbcuitmoonRoles the tbcuitmoonRoles to set
	 */
	public void setTbcuitmoonRoles(Set<TbcuitmoonRole> tbcuitmoonRoles) {
		this.tbcuitmoonRoles = tbcuitmoonRoles;
	}

}
