package edu.cuit.module.sys.entity;

// Generated 2015-4-13 16:59:09 by Hibernate Tools 4.3.1

/**
 * TbcuitmoonRolejurisdiction generated by hbm2java
 */
public class TbcuitmoonRolejurisdiction implements java.io.Serializable {

	private String cuitMoonRoleJurisdictionId;
	private String cuitMoonRoleId;
	private String cuitMoonJurisdictionId;

	public TbcuitmoonRolejurisdiction() {
	}

	public TbcuitmoonRolejurisdiction(String cuitMoonRoleJurisdictionId) {
		this.cuitMoonRoleJurisdictionId = cuitMoonRoleJurisdictionId;
	}

	public TbcuitmoonRolejurisdiction(String cuitMoonRoleJurisdictionId,
			String cuitMoonRoleId, String cuitMoonJurisdictionId) {
		this.cuitMoonRoleJurisdictionId = cuitMoonRoleJurisdictionId;
		this.cuitMoonRoleId = cuitMoonRoleId;
		this.cuitMoonJurisdictionId = cuitMoonJurisdictionId;
	}

	public String getCuitMoonRoleJurisdictionId() {
		return this.cuitMoonRoleJurisdictionId;
	}

	public void setCuitMoonRoleJurisdictionId(String cuitMoonRoleJurisdictionId) {
		this.cuitMoonRoleJurisdictionId = cuitMoonRoleJurisdictionId;
	}

	public String getCuitMoonRoleId() {
		return this.cuitMoonRoleId;
	}

	public void setCuitMoonRoleId(String cuitMoonRoleId) {
		this.cuitMoonRoleId = cuitMoonRoleId;
	}

	public String getCuitMoonJurisdictionId() {
		return this.cuitMoonJurisdictionId;
	}

	public void setCuitMoonJurisdictionId(String cuitMoonJurisdictionId) {
		this.cuitMoonJurisdictionId = cuitMoonJurisdictionId;
	}

}
