package edu.cuit.module.sys.entity;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import org.hibernate.validator.constraints.NotBlank;

// Generated 2015-4-13 16:59:09 by Hibernate Tools 4.3.1

/**
 * TbcuitmoonModule generated by hbm2java
 */
public class TbcuitmoonModule implements java.io.Serializable {

	private String cuitMoonModuleId;
	@NotBlank(message="名称不能为空")
	private String cuitMoonModuleName;
	private String cuitMoonModuleUrl;
	private String cuitMoonModuleIcon;
	private String cuitMoonParentModuleId;
	/* 自己添加的， 数据库中没有该字段 */
	private String cuitMoonParentModuleName;
	private Long cuitMoonModuleStatus;
	private Integer cuitMoonModuleOrderNum = 1;
	private String cuitMoonModuleDescription;
	private String cuitMoonModuleRemarks;
	
	private Set<TbcuitmoonJurisdiction> tbcuitmoonJurisdictions = new HashSet<TbcuitmoonJurisdiction>();
	private Set<TbcuitmoonModule> childModules = new HashSet<TbcuitmoonModule>();
	private List<TbcuitmoonModule> childModulesList = new ArrayList<TbcuitmoonModule>();
	public TbcuitmoonModule() {
	}

	public TbcuitmoonModule(String cuitMoonModuleId, String cuitMoonModuleName) {
		this.cuitMoonModuleId = cuitMoonModuleId;
		this.cuitMoonModuleName = cuitMoonModuleName;
	}

	public TbcuitmoonModule(String cuitMoonModuleId, String cuitMoonModuleName,
			String cuitMoonModuleUrl, String cuitMoonModuleIcon,
			String cuitMoonParentModuleId, Long cuitMoonModuleStatus,
			Integer cuitMoonModuleOrderNum, String cuitMoonModuleDescription,
			String cuitMoonModuleRemarks) {
		this.cuitMoonModuleId = cuitMoonModuleId;
		this.cuitMoonModuleName = cuitMoonModuleName;
		this.cuitMoonModuleUrl = cuitMoonModuleUrl;
		this.cuitMoonModuleIcon = cuitMoonModuleIcon;
		this.cuitMoonParentModuleId = cuitMoonParentModuleId;
		this.cuitMoonModuleStatus = cuitMoonModuleStatus;
		this.cuitMoonModuleOrderNum = cuitMoonModuleOrderNum;
		this.cuitMoonModuleDescription = cuitMoonModuleDescription;
		this.cuitMoonModuleRemarks = cuitMoonModuleRemarks;
	}

	public String getCuitMoonModuleId() {
		return this.cuitMoonModuleId;
	}

	public void setCuitMoonModuleId(String cuitMoonModuleId) {
		this.cuitMoonModuleId = cuitMoonModuleId;
	}

	public String getCuitMoonModuleName() {
		return this.cuitMoonModuleName;
	}

	public void setCuitMoonModuleName(String cuitMoonModuleName) {
		this.cuitMoonModuleName = cuitMoonModuleName;
	}

	public String getCuitMoonModuleUrl() {
		return this.cuitMoonModuleUrl;
	}

	public void setCuitMoonModuleUrl(String cuitMoonModuleUrl) {
		this.cuitMoonModuleUrl = cuitMoonModuleUrl;
	}

	public String getCuitMoonModuleIcon() {
		return this.cuitMoonModuleIcon;
	}

	public void setCuitMoonModuleIcon(String cuitMoonModuleIcon) {
		this.cuitMoonModuleIcon = cuitMoonModuleIcon;
	}

	public String getCuitMoonParentModuleId() {
		return this.cuitMoonParentModuleId;
	}

	public void setCuitMoonParentModuleId(String cuitMoonParentModuleId) {
		this.cuitMoonParentModuleId = cuitMoonParentModuleId;
	}

	public Long getCuitMoonModuleStatus() {
		return this.cuitMoonModuleStatus;
	}

	public void setCuitMoonModuleStatus(Long cuitMoonModuleStatus) {
		this.cuitMoonModuleStatus = cuitMoonModuleStatus;
	}

	public Integer getCuitMoonModuleOrderNum() {
		return this.cuitMoonModuleOrderNum;
	}

	public void setCuitMoonModuleOrderNum(Integer cuitMoonModuleOrderNum) {
		this.cuitMoonModuleOrderNum = cuitMoonModuleOrderNum;
	}

	public String getCuitMoonModuleDescription() {
		return this.cuitMoonModuleDescription;
	}

	public void setCuitMoonModuleDescription(String cuitMoonModuleDescription) {
		this.cuitMoonModuleDescription = cuitMoonModuleDescription;
	}

	public String getCuitMoonModuleRemarks() {
		return this.cuitMoonModuleRemarks;
	}

	public void setCuitMoonModuleRemarks(String cuitMoonModuleRemarks) {
		this.cuitMoonModuleRemarks = cuitMoonModuleRemarks;
	}

	public String getCuitMoonParentModuleName() {
		return cuitMoonParentModuleName;
	}

	public void setCuitMoonParentModuleName(String cuitMoonParentModuleName) {
		this.cuitMoonParentModuleName = cuitMoonParentModuleName;
	}

	/**
	 * @return the tbcuitmoonJurisdictions
	 */
	public Set<TbcuitmoonJurisdiction> getTbcuitmoonJurisdictions() {
		return tbcuitmoonJurisdictions;
	}

	/**
	 * @param tbcuitmoonJurisdictions the tbcuitmoonJurisdictions to set
	 */
	public void setTbcuitmoonJurisdictions(
			Set<TbcuitmoonJurisdiction> tbcuitmoonJurisdictions) {
		this.tbcuitmoonJurisdictions = tbcuitmoonJurisdictions;
	}

	/**
	 * @return the childModules
	 */
	public Set<TbcuitmoonModule> getChildModules() {
		return childModules;
	}

	/**
	 * @param childModules the childModules to set
	 */
	public void setChildModules(Set<TbcuitmoonModule> childModules) {
		this.childModules = childModules;
	}

	/**
	 * @return the childModulesList
	 */
	public List<TbcuitmoonModule> getChildModulesList() {
		return childModulesList;
	}

	/**
	 * @param childModulesList the childModulesList to set
	 */
	public void setChildModulesList(List<TbcuitmoonModule> childModulesList) {
		this.childModulesList = childModulesList;
	}
	
	
}
