package edu.cuit.module.sys.entity;

// Generated 2015-4-13 16:59:09 by Hibernate Tools 4.3.1

/**
 * TbcuitmoonRolemodule generated by hbm2java
 */
public class TbcuitmoonRolemodule implements java.io.Serializable {

	private String cuitMoonRoleModuleId;
	private String cuitMoonRoleId;
	private String cuitMoonModuleId;

	public TbcuitmoonRolemodule() {
	}

	public TbcuitmoonRolemodule(String cuitMoonRoleModuleId) {
		this.cuitMoonRoleModuleId = cuitMoonRoleModuleId;
	}

	public TbcuitmoonRolemodule(String cuitMoonRoleModuleId,
			String cuitMoonRoleId, String cuitMoonModuleId) {
		this.cuitMoonRoleModuleId = cuitMoonRoleModuleId;
		this.cuitMoonRoleId = cuitMoonRoleId;
		this.cuitMoonModuleId = cuitMoonModuleId;
	}

	public String getCuitMoonRoleModuleId() {
		return this.cuitMoonRoleModuleId;
	}

	public void setCuitMoonRoleModuleId(String cuitMoonRoleModuleId) {
		this.cuitMoonRoleModuleId = cuitMoonRoleModuleId;
	}

	public String getCuitMoonRoleId() {
		return this.cuitMoonRoleId;
	}

	public void setCuitMoonRoleId(String cuitMoonRoleId) {
		this.cuitMoonRoleId = cuitMoonRoleId;
	}

	public String getCuitMoonModuleId() {
		return this.cuitMoonModuleId;
	}

	public void setCuitMoonModuleId(String cuitMoonModuleId) {
		this.cuitMoonModuleId = cuitMoonModuleId;
	}

}
