package edu.cuit.module.sys.entity;

// Generated 2015-4-13 16:59:09 by Hibernate Tools 4.3.1

/**
 * TbcuitmoonDepartment generated by hbm2java
 */
public class TbcuitmoonDepartment implements java.io.Serializable {

	private String cuitMoonDepartmentId;
	private String cuitMoonDepartmentName;
	private String cuitMoonParentDepartmentId;
	private Long cuitMoonDepartmentStatus;
	private Integer cuitMoonDepartmentOrderNum;
	private String cuitMoonDepartmentRemarks;

	public TbcuitmoonDepartment() {
	}

	public TbcuitmoonDepartment(String cuitMoonDepartmentId,
			String cuitMoonDepartmentName) {
		this.cuitMoonDepartmentId = cuitMoonDepartmentId;
		this.cuitMoonDepartmentName = cuitMoonDepartmentName;
	}

	public TbcuitmoonDepartment(String cuitMoonDepartmentId,
			String cuitMoonDepartmentName, String cuitMoonParentDepartmentId,
			Long cuitMoonDepartmentStatus, Integer cuitMoonDepartmentOrderNum,
			String cuitMoonDepartmentRemarks) {
		this.cuitMoonDepartmentId = cuitMoonDepartmentId;
		this.cuitMoonDepartmentName = cuitMoonDepartmentName;
		this.cuitMoonParentDepartmentId = cuitMoonParentDepartmentId;
		this.cuitMoonDepartmentStatus = cuitMoonDepartmentStatus;
		this.cuitMoonDepartmentOrderNum = cuitMoonDepartmentOrderNum;
		this.cuitMoonDepartmentRemarks = cuitMoonDepartmentRemarks;
	}

	public String getCuitMoonDepartmentId() {
		return this.cuitMoonDepartmentId;
	}

	public void setCuitMoonDepartmentId(String cuitMoonDepartmentId) {
		this.cuitMoonDepartmentId = cuitMoonDepartmentId;
	}

	public String getCuitMoonDepartmentName() {
		return this.cuitMoonDepartmentName;
	}

	public void setCuitMoonDepartmentName(String cuitMoonDepartmentName) {
		this.cuitMoonDepartmentName = cuitMoonDepartmentName;
	}

	public String getCuitMoonParentDepartmentId() {
		return this.cuitMoonParentDepartmentId;
	}

	public void setCuitMoonParentDepartmentId(String cuitMoonParentDepartmentId) {
		this.cuitMoonParentDepartmentId = cuitMoonParentDepartmentId;
	}

	public Long getCuitMoonDepartmentStatus() {
		return this.cuitMoonDepartmentStatus;
	}

	public void setCuitMoonDepartmentStatus(Long cuitMoonDepartmentStatus) {
		this.cuitMoonDepartmentStatus = cuitMoonDepartmentStatus;
	}

	public Integer getCuitMoonDepartmentOrderNum() {
		return this.cuitMoonDepartmentOrderNum;
	}

	public void setCuitMoonDepartmentOrderNum(Integer cuitMoonDepartmentOrderNum) {
		this.cuitMoonDepartmentOrderNum = cuitMoonDepartmentOrderNum;
	}

	public String getCuitMoonDepartmentRemarks() {
		return this.cuitMoonDepartmentRemarks;
	}

	public void setCuitMoonDepartmentRemarks(String cuitMoonDepartmentRemarks) {
		this.cuitMoonDepartmentRemarks = cuitMoonDepartmentRemarks;
	}

}
