package edu.cuit.module.model.entity;

// Generated 2015-7-8 17:46:03 by Hibernate Tools 4.3.1

/**
 * Growthelement generated by hbm2java
 */
public class Growthelement implements java.io.Serializable {

	private String growthElemId;
	private String growthId;
	private String elementNumber;
	private String elementValue;

	public Growthelement() {
	}

	public Growthelement(String growthElemId) {
		this.growthElemId = growthElemId;
	}

	public Growthelement(String growthElemId, String growthId,
			String elementNumber, String elementValue) {
		this.growthElemId = growthElemId;
		this.growthId = growthId;
		this.elementNumber = elementNumber;
		this.elementValue = elementValue;
	}

	public String getGrowthElemId() {
		return this.growthElemId;
	}

	public void setGrowthElemId(String growthElemId) {
		this.growthElemId = growthElemId;
	}

	public String getGrowthId() {
		return this.growthId;
	}

	public void setGrowthId(String growthId) {
		this.growthId = growthId;
	}

	public String getElementNumber() {
		return this.elementNumber;
	}

	public void setElementNumber(String elementNumber) {
		this.elementNumber = elementNumber;
	}

	public String getElementValue() {
		return this.elementValue;
	}

	public void setElementValue(String elementValue) {
		this.elementValue = elementValue;
	}

}
