package edu.cuit.module.auchc.entity;

// Generated 2015-6-3 20:51:27 by Hibernate Tools 4.3.1

/**
 * Expertsgrade generated by hbm2java
 */
public class Expertsgrade implements java.io.Serializable {

	private String gradeBh;
	private String cropGrowthPeriod;
	private String timeRange;
	private String element;
	private String optimalRange;
	private String realCondition;
	private String gradeLevel;
	private Float gradeValue;
	private String bearingInfoId;
	private String expertsgradecol;

	public Expertsgrade() {
	}

	public Expertsgrade(String gradeBh) {
		this.gradeBh = gradeBh;
	}

	public Expertsgrade(String gradeBh, String cropGrowthPeriod,
			String timeRange, String element, String optimalRange,
			String realCondition, String gradeLevel, Float gradeValue,
			String bearingInfoId, String expertsgradecol) {
		this.gradeBh = gradeBh;
		this.cropGrowthPeriod = cropGrowthPeriod;
		this.timeRange = timeRange;
		this.element = element;
		this.optimalRange = optimalRange;
		this.realCondition = realCondition;
		this.gradeLevel = gradeLevel;
		this.gradeValue = gradeValue;
		this.bearingInfoId = bearingInfoId;
		this.expertsgradecol = expertsgradecol;
	}

	public String getGradeBh() {
		return this.gradeBh;
	}

	public void setGradeBh(String gradeBh) {
		this.gradeBh = gradeBh;
	}

	public String getCropGrowthPeriod() {
		return this.cropGrowthPeriod;
	}

	public void setCropGrowthPeriod(String cropGrowthPeriod) {
		this.cropGrowthPeriod = cropGrowthPeriod;
	}

	public String getTimeRange() {
		return this.timeRange;
	}

	public void setTimeRange(String timeRange) {
		this.timeRange = timeRange;
	}

	public String getElement() {
		return this.element;
	}

	public void setElement(String element) {
		this.element = element;
	}

	public String getOptimalRange() {
		return this.optimalRange;
	}

	public void setOptimalRange(String optimalRange) {
		this.optimalRange = optimalRange;
	}

	public String getRealCondition() {
		return this.realCondition;
	}

	public void setRealCondition(String realCondition) {
		this.realCondition = realCondition;
	}

	public String getGradeLevel() {
		return this.gradeLevel;
	}

	public void setGradeLevel(String gradeLevel) {
		this.gradeLevel = gradeLevel;
	}

	public Float getGradeValue() {
		return this.gradeValue;
	}

	public void setGradeValue(Float gradeValue) {
		this.gradeValue = gradeValue;
	}

	public String getBearingInfoId() {
		return this.bearingInfoId;
	}

	public void setBearingInfoId(String bearingInfoId) {
		this.bearingInfoId = bearingInfoId;
	}

	public String getExpertsgradecol() {
		return this.expertsgradecol;
	}

	public void setExpertsgradecol(String expertsgradecol) {
		this.expertsgradecol = expertsgradecol;
	}

}
