package edu.cuit.module.auchc.entity;

// Generated 2015-4-14 19:14:43 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Reportinfomation generated by hbm2java
 */
public class Reportinfomation implements java.io.Serializable {

	private String reportBh;
	private String applyBh;
	private String productInfomantion;
	private String producerImation;
	private String areaInfomation;
	private String approvelevel;
	private String approveConclusion;
	private String headleAgency;
	private String approveAgency;
	private Date reportAddTime;
	private String addPerson;
	private String remark;
	private String attachmentUrl;
	private String certificateImage;
	private String certificateAttachment;
	private String ifOther;
	private String languageType;

	public Reportinfomation() {
	}

	public Reportinfomation(String reportBh) {
		this.reportBh = reportBh;
	}

	public Reportinfomation(String reportBh, String applyBh,
			String productInfomantion, String producerImation,
			String areaInfomation, String approvelevel,
			String approveConclusion, String headleAgency,
			String approveAgency, Date reportAddTime, String addPerson,
			String remark, String attachmentUrl) {
		this.reportBh = reportBh;
		this.applyBh = applyBh;
		this.productInfomantion = productInfomantion;
		this.producerImation = producerImation;
		this.areaInfomation = areaInfomation;
		this.approvelevel = approvelevel;
		this.approveConclusion = approveConclusion;
		this.headleAgency = headleAgency;
		this.approveAgency = approveAgency;
		this.reportAddTime = reportAddTime;
		this.addPerson = addPerson;
		this.remark = remark;
		this.attachmentUrl = attachmentUrl;
	}

	public String getReportBh() {
		return this.reportBh;
	}

	public void setReportBh(String reportBh) {
		this.reportBh = reportBh;
	}

	public String getApplyBh() {
		return this.applyBh;
	}

	public void setApplyBh(String applyBh) {
		this.applyBh = applyBh;
	}

	public String getProductInfomantion() {
		return this.productInfomantion;
	}

	public void setProductInfomantion(String productInfomantion) {
		this.productInfomantion = productInfomantion;
	}

	public String getProducerImation() {
		return this.producerImation;
	}

	public void setProducerImation(String producerImation) {
		this.producerImation = producerImation;
	}

	public String getAreaInfomation() {
		return this.areaInfomation;
	}

	public void setAreaInfomation(String areaInfomation) {
		this.areaInfomation = areaInfomation;
	}

	public String getApprovelevel() {
		return this.approvelevel;
	}

	public void setApprovelevel(String approvelevel) {
		this.approvelevel = approvelevel;
	}

	public String getApproveConclusion() {
		return this.approveConclusion;
	}

	public void setApproveConclusion(String approveConclusion) {
		this.approveConclusion = approveConclusion;
	}

	public String getHeadleAgency() {
		return this.headleAgency;
	}

	public void setHeadleAgency(String headleAgency) {
		this.headleAgency = headleAgency;
	}

	public String getApproveAgency() {
		return this.approveAgency;
	}

	public void setApproveAgency(String approveAgency) {
		this.approveAgency = approveAgency;
	}

	public Date getReportAddTime() {
		return this.reportAddTime;
	}

	public void setReportAddTime(Date reportAddTime) {
		this.reportAddTime = reportAddTime;
	}

	public String getAddPerson() {
		return this.addPerson;
	}

	public void setAddPerson(String addPerson) {
		this.addPerson = addPerson;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getAttachmentUrl() {
		return this.attachmentUrl;
	}

	public void setAttachmentUrl(String attachmentUrl) {
		this.attachmentUrl = attachmentUrl;
	}

	/**
	 * @return the certificateImage
	 */
	public String getCertificateImage() {
		return certificateImage;
	}

	/**
	 * @param certificateImage the certificateImage to set
	 */
	public void setCertificateImage(String certificateImage) {
		this.certificateImage = certificateImage;
	}

	/**
	 * @return the certificateAttachment
	 */
	public String getCertificateAttachment() {
		return certificateAttachment;
	}

	/**
	 * @param certificateAttachment the certificateAttachment to set
	 */
	public void setCertificateAttachment(String certificateAttachment) {
		this.certificateAttachment = certificateAttachment;
	}

	/**
	 * @return the ifOther
	 */
	public String getIfOther() {
		return ifOther;
	}

	/**
	 * @param ifOther the ifOther to set
	 */
	public void setIfOther(String ifOther) {
		this.ifOther = ifOther;
	}

	/**
	 * @return the languageType
	 */
	public String getLanguageType() {
		return languageType;
	}

	/**
	 * @param languageType the languageType to set
	 */
	public void setLanguageType(String languageType) {
		this.languageType = languageType;
	}

}
