package edu.cuit.module.auchc.entity;

// Generated 2015-6-15 21:45:52 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Reportinfomationother generated by hbm2java
 */
public class Reportinfomationother implements java.io.Serializable {

	private String languageId;
	private String productInfomantion;
	private String producerImation;
	private String areaInfomation;
	private String approvelevel;
	private String approveConclusion;
	private String headleAgency;
	private String approveAgency;
	private Date reportAddTime;
	private String addPerson;
	private String remark;
	private String certificateImage;
	private String certificateAttachment;
	private String languageType;
	private String reportBh;

	public Reportinfomationother() {
	}

	public Reportinfomationother(String languageId, String reportBh) {
		this.languageId = languageId;
		this.reportBh = reportBh;
	}

	public Reportinfomationother(String languageId, String productInfomantion,
			String producerImation, String areaInfomation, String approvelevel,
			String approveConclusion, String headleAgency,
			String approveAgency, Date reportAddTime, String addPerson,
			String remark, String certificateImage,
			String certificateAttachment, String languageType, String reportBh) {
		this.languageId = languageId;
		this.productInfomantion = productInfomantion;
		this.producerImation = producerImation;
		this.areaInfomation = areaInfomation;
		this.approvelevel = approvelevel;
		this.approveConclusion = approveConclusion;
		this.headleAgency = headleAgency;
		this.approveAgency = approveAgency;
		this.reportAddTime = reportAddTime;
		this.addPerson = addPerson;
		this.remark = remark;
		this.certificateImage = certificateImage;
		this.certificateAttachment = certificateAttachment;
		this.languageType = languageType;
		this.reportBh = reportBh;
	}

	public String getLanguageId() {
		return this.languageId;
	}

	public void setLanguageId(String languageId) {
		this.languageId = languageId;
	}

	public String getProductInfomantion() {
		return this.productInfomantion;
	}

	public void setProductInfomantion(String productInfomantion) {
		this.productInfomantion = productInfomantion;
	}

	public String getProducerImation() {
		return this.producerImation;
	}

	public void setProducerImation(String producerImation) {
		this.producerImation = producerImation;
	}

	public String getAreaInfomation() {
		return this.areaInfomation;
	}

	public void setAreaInfomation(String areaInfomation) {
		this.areaInfomation = areaInfomation;
	}

	public String getApprovelevel() {
		return this.approvelevel;
	}

	public void setApprovelevel(String approvelevel) {
		this.approvelevel = approvelevel;
	}

	public String getApproveConclusion() {
		return this.approveConclusion;
	}

	public void setApproveConclusion(String approveConclusion) {
		this.approveConclusion = approveConclusion;
	}

	public String getHeadleAgency() {
		return this.headleAgency;
	}

	public void setHeadleAgency(String headleAgency) {
		this.headleAgency = headleAgency;
	}

	public String getApproveAgency() {
		return this.approveAgency;
	}

	public void setApproveAgency(String approveAgency) {
		this.approveAgency = approveAgency;
	}

	public Date getReportAddTime() {
		return this.reportAddTime;
	}

	public void setReportAddTime(Date reportAddTime) {
		this.reportAddTime = reportAddTime;
	}

	public String getAddPerson() {
		return this.addPerson;
	}

	public void setAddPerson(String addPerson) {
		this.addPerson = addPerson;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getCertificateImage() {
		return this.certificateImage;
	}

	public void setCertificateImage(String certificateImage) {
		this.certificateImage = certificateImage;
	}

	public String getCertificateAttachment() {
		return this.certificateAttachment;
	}

	public void setCertificateAttachment(String certificateAttachment) {
		this.certificateAttachment = certificateAttachment;
	}

	public String getLanguageType() {
		return this.languageType;
	}

	public void setLanguageType(String languageType) {
		this.languageType = languageType;
	}

	public String getReportBh() {
		return this.reportBh;
	}

	public void setReportBh(String reportBh) {
		this.reportBh = reportBh;
	}

}
