package edu.cuit.module.origin.entity;

// Generated 2015-4-14 22:06:25 by Hibernate Tools 4.3.1

/**
 * Certificate generated by hbm2java
 */
public class Certificate implements java.io.Serializable {

	private String certificateId;
	private String certificateName;
	private String pictureUrl;
	private String getTime;
	private String awardDepart;
	private String remark;
	private String originId;
	private String campanyNo;

	public Certificate() {
	}

	public Certificate(String certificateId) {
		this.certificateId = certificateId;
	}

	public Certificate(String certificateId, String certificateName,
			String pictureUrl, String getTime, String awardDepart,
			String remark, String originId, String campanyNo) {
		this.certificateId = certificateId;
		this.certificateName = certificateName;
		this.pictureUrl = pictureUrl;
		this.getTime = getTime;
		this.awardDepart = awardDepart;
		this.remark = remark;
		this.originId = originId;
		this.campanyNo = campanyNo;
	}

	public String getCertificateId() {
		return this.certificateId;
	}

	public void setCertificateId(String certificateId) {
		this.certificateId = certificateId;
	}

	public String getCertificateName() {
		return this.certificateName;
	}

	public void setCertificateName(String certificateName) {
		this.certificateName = certificateName;
	}

	public String getPictureUrl() {
		return this.pictureUrl;
	}

	public void setPictureUrl(String pictureUrl) {
		this.pictureUrl = pictureUrl;
	}

	public String getGetTime() {
		return this.getTime;
	}

	public void setGetTime(String getTime) {
		this.getTime = getTime;
	}

	public String getAwardDepart() {
		return this.awardDepart;
	}

	public void setAwardDepart(String awardDepart) {
		this.awardDepart = awardDepart;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getOriginId() {
		return this.originId;
	}

	public void setOriginId(String originId) {
		this.originId = originId;
	}

	public String getCampanyNo() {
		return this.campanyNo;
	}

	public void setCampanyNo(String campanyNo) {
		this.campanyNo = campanyNo;
	}

}
