package edu.cuit.module.infom.entity;

// Generated 2015-4-15 13:38:49 by Hibernate Tools 4.3.1

/**
 * Expertsgroup generated by hbm2java
 */
public class Expertsgroup implements java.io.Serializable {

	private String expertsId;//专家组编号
	private String expertsLevel;//专家组层次
	private String region;//所属区域
	private String expertsName;//专家组名称
	private String expertsPerson;//专家组成员

	public Expertsgroup() {
	}

	public Expertsgroup(String expertsId) {
		this.expertsId = expertsId;
	}

	public Expertsgroup(String expertsId, String expertsLevel, String region,
			String expertsName, String expertsPerson) {
		this.expertsId = expertsId;
		this.expertsLevel = expertsLevel;
		this.region = region;
		this.expertsName = expertsName;
		this.expertsPerson = expertsPerson;
	}

	public String getExpertsId() {
		return this.expertsId;
	}

	public void setExpertsId(String expertsId) {
		this.expertsId = expertsId;
	}

	public String getExpertsLevel() {
		return this.expertsLevel;
	}

	public void setExpertsLevel(String expertsLevel) {
		this.expertsLevel = expertsLevel;
	}

	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	public String getExpertsName() {
		return this.expertsName;
	}

	public void setExpertsName(String expertsName) {
		this.expertsName = expertsName;
	}

	public String getExpertsPerson() {
		return this.expertsPerson;
	}

	public void setExpertsPerson(String expertsPerson) {
		this.expertsPerson = expertsPerson;
	}

}
