package edu.cuit.module.auchc.entity;

// Generated 2015-4-14 19:14:43 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Disastoursdata generated by hbm2java
 */
public class Disastoursdata implements java.io.Serializable {

	private String dataCode;
	private String approveDataCode;
	private String dataOrigin;
	private String disastoursDescription;
	private Date addTime;
	private String remark;

	public Disastoursdata() {
	}

	public Disastoursdata(String dataCode, String approveDataCode) {
		this.dataCode = dataCode;
		this.approveDataCode = approveDataCode;
	}

	public Disastoursdata(String dataCode, String approveDataCode,
			String dataOrigin, String disastoursDescription, Date addTime,
			String remark) {
		this.dataCode = dataCode;
		this.approveDataCode = approveDataCode;
		this.dataOrigin = dataOrigin;
		this.disastoursDescription = disastoursDescription;
		this.addTime = addTime;
		this.remark = remark;
	}

	public String getDataCode() {
		return this.dataCode;
	}

	public void setDataCode(String dataCode) {
		this.dataCode = dataCode;
	}

	public String getApproveDataCode() {
		return this.approveDataCode;
	}

	public void setApproveDataCode(String approveDataCode) {
		this.approveDataCode = approveDataCode;
	}

	public String getDataOrigin() {
		return this.dataOrigin;
	}

	public void setDataOrigin(String dataOrigin) {
		this.dataOrigin = dataOrigin;
	}

	public String getDisastoursDescription() {
		return this.disastoursDescription;
	}

	public void setDisastoursDescription(String disastoursDescription) {
		this.disastoursDescription = disastoursDescription;
	}

	public Date getAddTime() {
		return this.addTime;
	}

	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
