package edu.cuit.module.auchc.entity;

// Generated 2015-4-14 19:14:43 by Hibernate Tools 4.3.1

/**
 * Approvedatamanager generated by hbm2java
 */
public class Approvedatamanager implements java.io.Serializable {

	private String approveDataCode;
	private String qualityIdentificationNum;
	private String dataKinds;
	private String remark;

	public Approvedatamanager() {
	}

	public Approvedatamanager(String approveDataCode,
			String qualityIdentificationNum) {
		this.approveDataCode = approveDataCode;
		this.qualityIdentificationNum = qualityIdentificationNum;
	}

	public Approvedatamanager(String approveDataCode,
			String qualityIdentificationNum, String dataKinds, String remark) {
		this.approveDataCode = approveDataCode;
		this.qualityIdentificationNum = qualityIdentificationNum;
		this.dataKinds = dataKinds;
		this.remark = remark;
	}

	public String getApproveDataCode() {
		return this.approveDataCode;
	}

	public void setApproveDataCode(String approveDataCode) {
		this.approveDataCode = approveDataCode;
	}

	public String getQualityIdentificationNum() {
		return this.qualityIdentificationNum;
	}

	public void setQualityIdentificationNum(String qualityIdentificationNum) {
		this.qualityIdentificationNum = qualityIdentificationNum;
	}

	public String getDataKinds() {
		return this.dataKinds;
	}

	public void setDataKinds(String dataKinds) {
		this.dataKinds = dataKinds;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
