package edu.cuit.module.entm.entity;

// Generated 2015-4-14 18:33:50 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * TbncpQiyeProduct generated by hbm2java
 */
public class TbncpQiyeProduct implements java.io.Serializable {

	private String productId;
	private String qiyenum;
	private Date cretime;
	private String productname;
	private String productimg;
	private String productcontent;

	public TbncpQiyeProduct() {
	}

	public TbncpQiyeProduct(String productId) {
		this.productId = productId;
	}

	public TbncpQiyeProduct(String productId, String qiyenum, Date cretime,
			String productname, String productimg, String productcontent) {
		this.productId = productId;
		this.qiyenum = qiyenum;
		this.cretime = cretime;
		this.productname = productname;
		this.productimg = productimg;
		this.productcontent = productcontent;
	}

	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	public String getQiyenum() {
		return this.qiyenum;
	}

	public void setQiyenum(String qiyenum) {
		this.qiyenum = qiyenum;
	}

	public Date getCretime() {
		return this.cretime;
	}

	public void setCretime(Date cretime) {
		this.cretime = cretime;
	}

	public String getProductname() {
		return this.productname;
	}

	public void setProductname(String productname) {
		this.productname = productname;
	}

	public String getProductimg() {
		return this.productimg;
	}

	public void setProductimg(String productimg) {
		this.productimg = productimg;
	}

	public String getProductcontent() {
		return this.productcontent;
	}

	public void setProductcontent(String productcontent) {
		this.productcontent = productcontent;
	}

}
