package edu.cuit.module.auchc.entity;

// Generated 2015-4-14 19:14:43 by Hibernate Tools 4.3.1

/**
 * Cimatequalityapproveprocess generated by hbm2java
 */
public class Cimatequalityapproveprocess implements java.io.Serializable {

	private String approveScheduleId;
	private String applyBh;
	private String scheduleIdProcess;
	private String projectName;
	private String time;

	public Cimatequalityapproveprocess() {
	}

	public Cimatequalityapproveprocess(String approveScheduleId) {
		this.approveScheduleId = approveScheduleId;
	}

	public Cimatequalityapproveprocess(String approveScheduleId,
			String applyBh, String scheduleIdProcess, String projectName,
			String time) {
		this.approveScheduleId = approveScheduleId;
		this.applyBh = applyBh;
		this.scheduleIdProcess = scheduleIdProcess;
		this.projectName = projectName;
		this.time = time;
	}

	public String getApproveScheduleId() {
		return this.approveScheduleId;
	}

	public void setApproveScheduleId(String approveScheduleId) {
		this.approveScheduleId = approveScheduleId;
	}

	public String getApplyBh() {
		return this.applyBh;
	}

	public void setApplyBh(String applyBh) {
		this.applyBh = applyBh;
	}

	public String getScheduleIdProcess() {
		return this.scheduleIdProcess;
	}

	public void setScheduleIdProcess(String scheduleIdProcess) {
		this.scheduleIdProcess = scheduleIdProcess;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	public String getTime() {
		return this.time;
	}

	public void setTime(String time) {
		this.time = time;
	}

}
