package edu.cuit.module.auchc.entity;

// Generated 2015-4-14 19:14:43 by Hibernate Tools 4.3.1

/**
 * IdentificationRecord generated by hbm2java
 */
public class IdentificationRecord implements java.io.Serializable {

	private String recordNum;
	private String applyBh;
	private String fileCode;
	private String projectName;
	private String archivePeople;
	private String filingTime;
	private String remark;

	public IdentificationRecord() {
	}

	public IdentificationRecord(String recordNum) {
		this.recordNum = recordNum;
	}

	public IdentificationRecord(String recordNum, String applyBh,
			String fileCode, String projectName, String archivePeople,
			String filingTime, String remark) {
		this.recordNum = recordNum;
		this.applyBh = applyBh;
		this.fileCode = fileCode;
		this.projectName = projectName;
		this.archivePeople = archivePeople;
		this.filingTime = filingTime;
		this.remark = remark;
	}

	public String getRecordNum() {
		return this.recordNum;
	}

	public void setRecordNum(String recordNum) {
		this.recordNum = recordNum;
	}

	public String getApplyBh() {
		return this.applyBh;
	}

	public void setApplyBh(String applyBh) {
		this.applyBh = applyBh;
	}

	public String getFileCode() {
		return this.fileCode;
	}

	public void setFileCode(String fileCode) {
		this.fileCode = fileCode;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	public String getArchivePeople() {
		return this.archivePeople;
	}

	public void setArchivePeople(String archivePeople) {
		this.archivePeople = archivePeople;
	}

	public String getFilingTime() {
		return this.filingTime;
	}

	public void setFilingTime(String filingTime) {
		this.filingTime = filingTime;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
