package edu.cuit.module.infom.entity;

// Generated 2015-5-14 17:06:53 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Businessqualification generated by hbm2java
 */
public class Businessqualification implements java.io.Serializable {

	private String businessId;
	private String name;
	private String awardTime;
	private String publishUnit;
	private String picUrl;
	private String companyNo;

	public Businessqualification() {
	}

	public Businessqualification(String businessId) {
		this.businessId = businessId;
	}

	public Businessqualification(String businessId, String name,
			String awardTime, String publishUnit, String picUrl, String companyNo) {
		this.businessId = businessId;
		this.name = name;
		this.awardTime = awardTime;
		this.publishUnit = publishUnit;
		this.picUrl = picUrl;
		this.companyNo = companyNo;
	}

	public String getBusinessId() {
		return this.businessId;
	}

	public void setBusinessId(String businessId) {
		this.businessId = businessId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAwardTime() {
		return this.awardTime;
	}

	public void setAwardTime(String awardTime) {
		this.awardTime = awardTime;
	}

	public String getPublishUnit() {
		return this.publishUnit;
	}

	public void setPublishUnit(String publishUnit) {
		this.publishUnit = publishUnit;
	}

	public String getPicUrl() {
		return this.picUrl;
	}

	public void setPicUrl(String picUrl) {
		this.picUrl = picUrl;
	}

	public String getCompanyNo() {
		return this.companyNo;
	}

	public void setCompanyNo(String companyNo) {
		this.companyNo = companyNo;
	}

}
