package edu.cuit.module.infom.entity;

// Generated 2015-4-15 13:38:49 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Checkcenternewsreport generated by hbm2java
 */
public class Checkcenternewsreport implements java.io.Serializable {

	private String newsNumber;//新闻编号
	private String newsTitle;//新闻标题
	private String newsKey;//新闻关键字
	private String newsCategory;//新闻类别
	private String chargePictureNews;//是否是图片新闻
	private String pictureUrl;//图片
	private String text;//正文
	private Long sort;//排序
	private Long hits;//点击量
	private String newsState;//新闻状态
	private String attachmentUrl;//附件
	private Date reportTime;//发布时间
	private String reportName;//发布人
	private String remark;//备注

	public Checkcenternewsreport() {
	}

	public Checkcenternewsreport(String newsNumber) {
		this.newsNumber = newsNumber;
	}

	public Checkcenternewsreport(String newsNumber, String newsTitle,
			String newsKey, String newsCategory, String chargePictureNews,
			String pictureUrl, String text, Long sort, Long hits,
			String newsState, String attachmentUrl, Date reportTime,
			String reportName, String remark) {
		this.newsNumber = newsNumber;
		this.newsTitle = newsTitle;
		this.newsKey = newsKey;
		this.newsCategory = newsCategory;
		this.chargePictureNews = chargePictureNews;
		this.pictureUrl = pictureUrl;
		this.text = text;
		this.sort = sort;
		this.hits = hits;
		this.newsState = newsState;
		this.attachmentUrl = attachmentUrl;
		this.reportTime = reportTime;
		this.reportName = reportName;
		this.remark = remark;
	}

	public String getNewsNumber() {
		return this.newsNumber;
	}

	public void setNewsNumber(String newsNumber) {
		this.newsNumber = newsNumber;
	}

	public String getNewsTitle() {
		return this.newsTitle;
	}

	public void setNewsTitle(String newsTitle) {
		this.newsTitle = newsTitle;
	}

	public String getNewsKey() {
		return this.newsKey;
	}

	public void setNewsKey(String newsKey) {
		this.newsKey = newsKey;
	}

	public String getNewsCategory() {
		return this.newsCategory;
	}

	public void setNewsCategory(String newsCategory) {
		this.newsCategory = newsCategory;
	}

	public String getChargePictureNews() {
		return this.chargePictureNews;
	}

	public void setChargePictureNews(String chargePictureNews) {
		this.chargePictureNews = chargePictureNews;
	}

	public String getPictureUrl() {
		return this.pictureUrl;
	}

	public void setPictureUrl(String pictureUrl) {
		this.pictureUrl = pictureUrl;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public Long getSort() {
		return this.sort;
	}

	public void setSort(Long sort) {
		this.sort = sort;
	}

	public Long getHits() {
		return this.hits;
	}

	public void setHits(Long hits) {
		this.hits = hits;
	}

	public String getNewsState() {
		return this.newsState;
	}

	public void setNewsState(String newsState) {
		this.newsState = newsState;
	}

	public String getAttachmentUrl() {
		return this.attachmentUrl;
	}

	public void setAttachmentUrl(String attachmentUrl) {
		this.attachmentUrl = attachmentUrl;
	}

	public Date getReportTime() {
		return this.reportTime;
	}

	public void setReportTime(Date reportTime) {
		this.reportTime = reportTime;
	}

	public String getReportName() {
		return this.reportName;
	}

	public void setReportName(String reportName) {
		this.reportName = reportName;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
