package edu.cuit.module.infom.entity;

// Generated 2015-4-15 13:38:49 by Hibernate Tools 4.3.1

/**
 * Weatherstationinfo generated by hbm2java
 */
public class Weatherstationinfo implements java.io.Serializable {

	private String weatherStationInfoId;//气象站信息编号
	private String weatherStationId;//气象站编号
	private String name;//名称
	private String belongTo;//所属气象局
	private String longitude;//经度
	private String latitude;//纬度
	private String measuringelements;//测量要素
	private String remark;//备注

	public Weatherstationinfo() {
	}

	public Weatherstationinfo(String weatherStationInfoId) {
		this.weatherStationInfoId = weatherStationInfoId;
	}

	public Weatherstationinfo(String weatherStationInfoId,
			String weatherStationId, String name, String belongTo,
			String longitude, String latitude, String measuringelements,
			String remark) {
		this.weatherStationInfoId = weatherStationInfoId;
		this.weatherStationId = weatherStationId;
		this.name = name;
		this.belongTo = belongTo;
		this.longitude = longitude;
		this.latitude = latitude;
		this.measuringelements = measuringelements;
		this.remark = remark;
	}

	public String getWeatherStationInfoId() {
		return this.weatherStationInfoId;
	}

	public void setWeatherStationInfoId(String weatherStationInfoId) {
		this.weatherStationInfoId = weatherStationInfoId;
	}

	public String getWeatherStationId() {
		return this.weatherStationId;
	}

	public void setWeatherStationId(String weatherStationId) {
		this.weatherStationId = weatherStationId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getBelongTo() {
		return this.belongTo;
	}

	public void setBelongTo(String belongTo) {
		this.belongTo = belongTo;
	}

	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	public String getMeasuringelements() {
		return this.measuringelements;
	}

	public void setMeasuringelements(String measuringelements) {
		this.measuringelements = measuringelements;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
