package edu.cuit.module.model.entity;

// Generated 2015-4-14 21:24:14 by Hibernate Tools 4.3.1

/**
 * Elementinfomation generated by hbm2java
 */
public class Elementinfomation implements java.io.Serializable {

	private String certificationNumber;
	private String remark;
	private String elementNumber;
	private String productApproModelId;

	public Elementinfomation() {
	}

	public Elementinfomation(String certificationNumber) {
		this.certificationNumber = certificationNumber;
	}

	public Elementinfomation(String certificationNumber, String remark,
			String elementNumber, String productApproModelId) {
		this.certificationNumber = certificationNumber;
		this.remark = remark;
		this.elementNumber = elementNumber;
		this.productApproModelId = productApproModelId;
	}

	public String getCertificationNumber() {
		return this.certificationNumber;
	}

	public void setCertificationNumber(String certificationNumber) {
		this.certificationNumber = certificationNumber;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getElementNumber() {
		return this.elementNumber;
	}

	public void setElementNumber(String elementNumber) {
		this.elementNumber = elementNumber;
	}

	public String getProductApproModelId() {
		return this.productApproModelId;
	}

	public void setProductApproModelId(String productApproModelId) {
		this.productApproModelId = productApproModelId;
	}

}
