package edu.cuit.module.label.entity;

// Generated 2015-4-14 20:41:11 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Labelapplication generated by hbm2java
 */
public class Labelapplication implements java.io.Serializable {

	private String labelApplicationId;
	private String labelMakeStatus;
	private String labelPayment;
	private Date paymentTime;
	private String labelStyle;
	private String receiveStatus;
	private String applyType;
	private String applyBh;
	private String applyReason;
	private String applyStatus;
	private String applyPerson;
	private Date applyTime;
	private String confirmor;
	private Date confirmTime;
	private String inTotal;
	private String piCi;
	private String format;
	private String image;

	public Labelapplication() {
	}

	public Labelapplication(String labelApplicationId) {
		this.labelApplicationId = labelApplicationId;
	}

	public Labelapplication(String labelApplicationId, String labelMakeStatus,
			String labelPayment, Date paymentTime, String labelStyle,
			String receiveStatus, String applyType, String applyBh,
			String applyReason, String applyStatus, String applyPerson,
			Date applyTime, String confirmor, Date confirmTime, String inTotal,
			String piCi) {
		this.labelApplicationId = labelApplicationId;
		this.labelMakeStatus = labelMakeStatus;
		this.labelPayment = labelPayment;
		this.paymentTime = paymentTime;
		this.labelStyle = labelStyle;
		this.receiveStatus = receiveStatus;
		this.applyType = applyType;
		this.applyBh = applyBh;
		this.applyReason = applyReason;
		this.applyStatus = applyStatus;
		this.applyPerson = applyPerson;
		this.applyTime = applyTime;
		this.confirmor = confirmor;
		this.confirmTime = confirmTime;
		this.inTotal = inTotal;
		this.piCi = piCi;
	}

	public String getLabelApplicationId() {
		return this.labelApplicationId;
	}

	public void setLabelApplicationId(String labelApplicationId) {
		this.labelApplicationId = labelApplicationId;
	}

	public String getLabelMakeStatus() {
		return this.labelMakeStatus;
	}

	public void setLabelMakeStatus(String labelMakeStatus) {
		this.labelMakeStatus = labelMakeStatus;
	}

	public String getLabelPayment() {
		return this.labelPayment;
	}

	public void setLabelPayment(String labelPayment) {
		this.labelPayment = labelPayment;
	}

	public Date getPaymentTime() {
		return this.paymentTime;
	}

	public void setPaymentTime(Date paymentTime) {
		this.paymentTime = paymentTime;
	}

	public String getLabelStyle() {
		return this.labelStyle;
	}

	public void setLabelStyle(String labelStyle) {
		this.labelStyle = labelStyle;
	}

	public String getReceiveStatus() {
		return this.receiveStatus;
	}

	public void setReceiveStatus(String receiveStatus) {
		this.receiveStatus = receiveStatus;
	}

	public String getApplyType() {
		return this.applyType;
	}

	public void setApplyType(String applyType) {
		this.applyType = applyType;
	}

	public String getApplyBh() {
		return this.applyBh;
	}

	public void setApplyBh(String applyBh) {
		this.applyBh = applyBh;
	}

	public String getApplyReason() {
		return this.applyReason;
	}

	public void setApplyReason(String applyReason) {
		this.applyReason = applyReason;
	}

	public String getApplyStatus() {
		return this.applyStatus;
	}

	public void setApplyStatus(String applyStatus) {
		this.applyStatus = applyStatus;
	}

	public String getApplyPerson() {
		return this.applyPerson;
	}

	public void setApplyPerson(String applyPerson) {
		this.applyPerson = applyPerson;
	}

	public Date getApplyTime() {
		return this.applyTime;
	}

	public void setApplyTime(Date applyTime) {
		this.applyTime = applyTime;
	}

	public String getConfirmor() {
		return this.confirmor;
	}

	public void setConfirmor(String confirmor) {
		this.confirmor = confirmor;
	}

	public Date getConfirmTime() {
		return this.confirmTime;
	}

	public void setConfirmTime(Date confirmTime) {
		this.confirmTime = confirmTime;
	}

	public String getInTotal() {
		return this.inTotal;
	}

	public void setInTotal(String inTotal) {
		this.inTotal = inTotal;
	}

	public String getPiCi() {
		return this.piCi;
	}

	public void setPiCi(String piCi) {
		this.piCi = piCi;
	}

	public String getFormat() {
		return format;
	}

	public void setFormat(String format) {
		this.format = format;
	}

	public String getImage() {
		return image;
	}

	public void setImage(String image) {
		this.image = image;
	}

}
