package edu.cuit.module.label.entity;

// Generated 2015-4-14 20:41:11 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Labelproviderecord generated by hbm2java
 */
public class Labelproviderecord implements java.io.Serializable {

	private String receiveId;
	private String applyBh;
	private int receiveAmount;
	private String receivePerson;
	private Date receiveTime;
	private String originId;

	public Labelproviderecord() {
	}

	public Labelproviderecord(String receiveId, int receiveAmount) {
		this.receiveId = receiveId;
		this.receiveAmount = receiveAmount;
	}

	public Labelproviderecord(String receiveId, String applyBh,
			int receiveAmount, String receivePerson, Date receiveTime,
			String originId) {
		this.receiveId = receiveId;
		this.applyBh = applyBh;
		this.receiveAmount = receiveAmount;
		this.receivePerson = receivePerson;
		this.receiveTime = receiveTime;
		this.originId = originId;
	}

	public String getReceiveId() {
		return this.receiveId;
	}

	public void setReceiveId(String receiveId) {
		this.receiveId = receiveId;
	}

	public String getApplyBh() {
		return this.applyBh;
	}

	public void setApplyBh(String applyBh) {
		this.applyBh = applyBh;
	}

	public int getReceiveAmount() {
		return this.receiveAmount;
	}

	public void setReceiveAmount(int receiveAmount) {
		this.receiveAmount = receiveAmount;
	}

	public String getReceivePerson() {
		return this.receivePerson;
	}

	public void setReceivePerson(String receivePerson) {
		this.receivePerson = receivePerson;
	}

	public Date getReceiveTime() {
		return this.receiveTime;
	}

	public void setReceiveTime(Date receiveTime) {
		this.receiveTime = receiveTime;
	}

	public String getOriginId() {
		return this.originId;
	}

	public void setOriginId(String originId) {
		this.originId = originId;
	}

}
