package edu.cuit.module.label.entity;

// Generated 2015-4-14 20:41:11 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Labelidmanage generated by hbm2java
 */
public class Labelidmanage implements java.io.Serializable {

	private String labelId;
	private String productName;
	private String companyName;
	private String certificateName;
	private String applyBh;
	private String originId;
	private String labelType;
	private Date manufactureTime;
	private String labelStatus;
	private Integer scanTimes;
	private String remark;

	public Labelidmanage() {
	}

	public Labelidmanage(String labelId) {
		this.labelId = labelId;
	}

	public Labelidmanage(String labelId, String productName,
			String companyName, String certificateName, String applyBh,
			String originId, String labelType, Date manufactureTime,
			String labelStatus, Integer scanTimes, String remark) {
		this.labelId = labelId;
		this.productName = productName;
		this.companyName = companyName;
		this.certificateName = certificateName;
		this.applyBh = applyBh;
		this.originId = originId;
		this.labelType = labelType;
		this.manufactureTime = manufactureTime;
		this.labelStatus = labelStatus;
		this.scanTimes = scanTimes;
		this.remark = remark;
	}

	public String getLabelId() {
		return this.labelId;
	}

	public void setLabelId(String labelId) {
		this.labelId = labelId;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	public String getCertificateName() {
		return this.certificateName;
	}

	public void setCertificateName(String certificateName) {
		this.certificateName = certificateName;
	}

	public String getApplyBh() {
		return this.applyBh;
	}

	public void setApplyBh(String applyBh) {
		this.applyBh = applyBh;
	}

	public String getOriginId() {
		return this.originId;
	}

	public void setOriginId(String originId) {
		this.originId = originId;
	}

	public String getLabelType() {
		return this.labelType;
	}

	public void setLabelType(String labelType) {
		this.labelType = labelType;
	}

	public Date getManufactureTime() {
		return this.manufactureTime;
	}

	public void setManufactureTime(Date manufactureTime) {
		this.manufactureTime = manufactureTime;
	}

	public String getLabelStatus() {
		return this.labelStatus;
	}

	public void setLabelStatus(String labelStatus) {
		this.labelStatus = labelStatus;
	}

	public Integer getScanTimes() {
		return this.scanTimes;
	}

	public void setScanTimes(Integer scanTimes) {
		this.scanTimes = scanTimes;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
