package edu.cuit.module.label.entity;

// Generated 2015-4-14 20:41:11 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Payrecord generated by hbm2java
 */
public class Payrecord implements java.io.Serializable {

	private String payRecordId;
	private String payPerson;
	private String inTotal;
	private Date payTime;
	private String payType;
	private String payId;

	public Payrecord() {
	}

	public Payrecord(String payRecordId) {
		this.payRecordId = payRecordId;
	}

	public Payrecord(String payRecordId, String payPerson, String inTotal,
			Date payTime, String payType, String payId) {
		this.payRecordId = payRecordId;
		this.payPerson = payPerson;
		this.inTotal = inTotal;
		this.payTime = payTime;
		this.payType = payType;
		this.payId = payId;
	}

	public String getPayRecordId() {
		return this.payRecordId;
	}

	public void setPayRecordId(String payRecordId) {
		this.payRecordId = payRecordId;
	}

	public String getPayPerson() {
		return this.payPerson;
	}

	public void setPayPerson(String payPerson) {
		this.payPerson = payPerson;
	}

	public String getInTotal() {
		return this.inTotal;
	}

	public void setInTotal(String inTotal) {
		this.inTotal = inTotal;
	}

	public Date getPayTime() {
		return this.payTime;
	}

	public void setPayTime(Date payTime) {
		this.payTime = payTime;
	}

	public String getPayType() {
		return this.payType;
	}

	public void setPayType(String payType) {
		this.payType = payType;
	}

	public String getPayId() {
		return this.payId;
	}

	public void setPayId(String payId) {
		this.payId = payId;
	}

}
