package edu.cuit.module.label.entity;

// Generated 2015-4-14 20:41:11 by Hibernate Tools 4.3.1

/**
 * Providecodecase generated by hbm2java
 */
public class Providecodecase implements java.io.Serializable {

	private String provideCode;
	private String labelId;
	private String receiveId;

	public Providecodecase() {
	}

	public Providecodecase(String provideCode) {
		this.provideCode = provideCode;
	}

	public Providecodecase(String provideCode, String labelId, String receiveId) {
		this.provideCode = provideCode;
		this.labelId = labelId;
		this.receiveId = receiveId;
	}

	public String getProvideCode() {
		return this.provideCode;
	}

	public void setProvideCode(String provideCode) {
		this.provideCode = provideCode;
	}

	public String getLabelId() {
		return this.labelId;
	}

	public void setLabelId(String labelId) {
		this.labelId = labelId;
	}

	public String getReceiveId() {
		return this.receiveId;
	}

	public void setReceiveId(String receiveId) {
		this.receiveId = receiveId;
	}

}
