package edu.cuit.module.model.entity;

// Generated 2015-4-14 21:24:14 by Hibernate Tools 4.3.1

/**
 * Approvemodelmanage generated by hbm2java
 */
public class Approvemodelmanage implements java.io.Serializable {

	private String approveLevelId;
	private String productApproModelId;
	private String approveLevelName;
	private String approveLevelDescription;
	private String remark;

	public Approvemodelmanage() {
	}

	public Approvemodelmanage(String approveLevelId) {
		this.approveLevelId = approveLevelId;
	}

	public Approvemodelmanage(String approveLevelId,
			String productApproModelId, String approveLevelName,
			String approveLevelDescription, String remark) {
		this.approveLevelId = approveLevelId;
		this.productApproModelId = productApproModelId;
		this.approveLevelName = approveLevelName;
		this.approveLevelDescription = approveLevelDescription;
		this.remark = remark;
	}

	public String getApproveLevelId() {
		return this.approveLevelId;
	}

	public void setApproveLevelId(String approveLevelId) {
		this.approveLevelId = approveLevelId;
	}

	public String getProductApproModelId() {
		return this.productApproModelId;
	}

	public void setProductApproModelId(String productApproModelId) {
		this.productApproModelId = productApproModelId;
	}

	public String getApproveLevelName() {
		return this.approveLevelName;
	}

	public void setApproveLevelName(String approveLevelName) {
		this.approveLevelName = approveLevelName;
	}

	public String getApproveLevelDescription() {
		return this.approveLevelDescription;
	}

	public void setApproveLevelDescription(String approveLevelDescription) {
		this.approveLevelDescription = approveLevelDescription;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
