package edu.cuit.module.model.entity;

// Generated 2015-4-14 21:24:14 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Elementmodel generated by hbm2java
 */
public class Elementmodel implements java.io.Serializable {

	private String elementNumber;
	private String unit;
	private String elementName;
	private String elementType;
	private String elementDecription;
	private Date addTime;
	private String remark;
	private String climateStation;

	public Elementmodel() {
	}

	public Elementmodel(String elementNumber, String elementName,
			String elementType) {
		this.elementNumber = elementNumber;
		this.elementName = elementName;
		this.elementType = elementType;
	}

	public Elementmodel(String elementNumber, String unit, String elementName,
			String elementType, String elementDecription, Date addTime,
			String remark, String climateStation) {
		this.elementNumber = elementNumber;
		this.unit = unit;
		this.elementName = elementName;
		this.elementType = elementType;
		this.elementDecription = elementDecription;
		this.addTime = addTime;
		this.remark = remark;
		this.climateStation = climateStation;
	}

	public String getElementNumber() {
		return this.elementNumber;
	}

	public void setElementNumber(String elementNumber) {
		this.elementNumber = elementNumber;
	}

	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	public String getElementName() {
		return this.elementName;
	}

	public void setElementName(String elementName) {
		this.elementName = elementName;
	}

	public String getElementType() {
		return this.elementType;
	}

	public void setElementType(String elementType) {
		this.elementType = elementType;
	}

	public String getElementDecription() {
		return this.elementDecription;
	}

	public void setElementDecription(String elementDecription) {
		this.elementDecription = elementDecription;
	}

	public Date getAddTime() {
		return this.addTime;
	}

	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getClimateStation() {
		return this.climateStation;
	}

	public void setClimateStation(String climateStation) {
		this.climateStation = climateStation;
	}

}
