package edu.cuit.module.auchc.entity;

// Generated 2015-4-14 19:14:43 by Hibernate Tools 4.3.1

/**
 * MemberGroup generated by hbm2java
 */
public class MemberGroup implements java.io.Serializable {

	private String memberNum;
	private String expertsNum;
	private String member;
	private String isGrouper;

	public MemberGroup() {
	}

	public MemberGroup(String memberNum) {
		this.memberNum = memberNum;
	}

	public MemberGroup(String memberNum, String expertsNum, String member,
			String isGrouper) {
		this.memberNum = memberNum;
		this.expertsNum = expertsNum;
		this.member = member;
		this.isGrouper = isGrouper;
	}

	public String getMemberNum() {
		return this.memberNum;
	}

	public void setMemberNum(String memberNum) {
		this.memberNum = memberNum;
	}

	public String getExpertsNum() {
		return this.expertsNum;
	}

	public void setExpertsNum(String expertsNum) {
		this.expertsNum = expertsNum;
	}

	public String getMember() {
		return this.member;
	}

	public void setMember(String member) {
		this.member = member;
	}

	public String getIsGrouper() {
		return this.isGrouper;
	}

	public void setIsGrouper(String isGrouper) {
		this.isGrouper = isGrouper;
	}

}
