package edu.cuit.module.model.entity;

// Generated 2015-4-14 21:24:14 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Productinfomation generated by hbm2java
 */
public class Productinfomation implements java.io.Serializable {

	private String productNumber;
	private String productName;
	private String productType;
	private String productDescription;
	private Date addTime;
	private String remark;
	private String productTypeAclass;
	private String productTypeBclass;
	private String productCode;

	public Productinfomation() {
	}

	public Productinfomation(String productNumber) {
		this.productNumber = productNumber;
	}

	public Productinfomation(String productNumber, String productName,
			String productType, String productDescription, Date addTime,
			String remark, String productTypeAclass, String productTypeBclass,
			String productCode) {
		this.productNumber = productNumber;
		this.productName = productName;
		this.productType = productType;
		this.productDescription = productDescription;
		this.addTime = addTime;
		this.remark = remark;
		this.productTypeAclass = productTypeAclass;
		this.productTypeBclass = productTypeBclass;
		this.productCode = productCode;
	}

	public String getProductNumber() {
		return this.productNumber;
	}

	public void setProductNumber(String productNumber) {
		this.productNumber = productNumber;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public String getProductType() {
		return this.productType;
	}

	public void setProductType(String productType) {
		this.productType = productType;
	}

	public String getProductDescription() {
		return this.productDescription;
	}

	public void setProductDescription(String productDescription) {
		this.productDescription = productDescription;
	}

	public Date getAddTime() {
		return this.addTime;
	}

	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getProductTypeAclass() {
		return this.productTypeAclass;
	}

	public void setProductTypeAclass(String productTypeAclass) {
		this.productTypeAclass = productTypeAclass;
	}

	public String getProductTypeBclass() {
		return this.productTypeBclass;
	}

	public void setProductTypeBclass(String productTypeBclass) {
		this.productTypeBclass = productTypeBclass;
	}

	public String getProductCode() {
		return this.productCode;
	}

	public void setProductCode(String productCode) {
		this.productCode = productCode;
	}

}
