package edu.cuit.module.auchc.entity;

// Generated 2015-4-14 19:14:43 by Hibernate Tools 4.3.1

/**
 * ClimateQualitycertificationExperts generated by hbm2java
 */
public class ClimateQualitycertificationExperts implements java.io.Serializable {

	private String expertsNum;
	private String applyBh;
	private String expertsLevel;
	private String expertsClass;
	private String remark;

	public ClimateQualitycertificationExperts() {
	}

	public ClimateQualitycertificationExperts(String expertsNum) {
		this.expertsNum = expertsNum;
	}

	public ClimateQualitycertificationExperts(String expertsNum,
			String applyBh, String expertsLevel, String expertsClass,
			String remark) {
		this.expertsNum = expertsNum;
		this.applyBh = applyBh;
		this.expertsLevel = expertsLevel;
		this.expertsClass = expertsClass;
		this.remark = remark;
	}

	public String getExpertsNum() {
		return this.expertsNum;
	}

	public void setExpertsNum(String expertsNum) {
		this.expertsNum = expertsNum;
	}

	public String getApplyBh() {
		return this.applyBh;
	}

	public void setApplyBh(String applyBh) {
		this.applyBh = applyBh;
	}

	public String getExpertsLevel() {
		return this.expertsLevel;
	}

	public void setExpertsLevel(String expertsLevel) {
		this.expertsLevel = expertsLevel;
	}

	public String getExpertsClass() {
		return this.expertsClass;
	}

	public void setExpertsClass(String expertsClass) {
		this.expertsClass = expertsClass;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
