package edu.cuit.module.auchc.entity;

// Generated 2015-4-14 19:14:43 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * QualityIdentification generated by hbm2java
 */
public class QualityIdentification implements java.io.Serializable {

	private String qualityIdentificationNum;
	private String applyBh;
	private String projectName;
	private String expertsNum;
	private String applyFrequency;
	private String identificationer;
	private String phone;
	private String address;
	private String cropGrowthPeriod;
	private String originSituation;
	private String meteorologicalDisaster;
	private String diseasesInsectPests;
	private String basicPanelAuditOpinion;
	private String basicPanelSign;
	private Date basicAuditTime;
	private String provincialPanelAuditOpinion;
	private String provincialPanelSign;
	private Date provincialAuditTime;
	private String meteDataSources;
	private String meteLongitudeLatitude;
	private String meteIndicators;
	private String meteIndicatorsReason;
	private String state;
	private String remark;
	private String produceBase;
	private String stationLatitude;
	private String climateStationName;
	private Date startCollectionTime;
	private Date endCollectionTime;

	public QualityIdentification() {
	}

	public QualityIdentification(String qualityIdentificationNum) {
		this.qualityIdentificationNum = qualityIdentificationNum;
	}

	public QualityIdentification(String qualityIdentificationNum,
			String applyBh, String projectName, String expertsNum,
			String applyFrequency, String identificationer, String phone,
			String address, String cropGrowthPeriod, String originSituation,
			String meteorologicalDisaster, String diseasesInsectPests,
			String basicPanelAuditOpinion, String basicPanelSign,
			Date basicAuditTime, String provincialPanelAuditOpinion,
			String provincialPanelSign, Date provincialAuditTime,
			String meteDataSources, String meteLongitudeLatitude,
			String meteIndicators, String meteIndicatorsReason, String state,
			String remark, String produceBase, String stationLatitude,
			String climateStationName, Date startCollectionTime,
			Date endCollectionTime) {
		this.qualityIdentificationNum = qualityIdentificationNum;
		this.applyBh = applyBh;
		this.projectName = projectName;
		this.expertsNum = expertsNum;
		this.applyFrequency = applyFrequency;
		this.identificationer = identificationer;
		this.phone = phone;
		this.address = address;
		this.cropGrowthPeriod = cropGrowthPeriod;
		this.originSituation = originSituation;
		this.meteorologicalDisaster = meteorologicalDisaster;
		this.diseasesInsectPests = diseasesInsectPests;
		this.basicPanelAuditOpinion = basicPanelAuditOpinion;
		this.basicPanelSign = basicPanelSign;
		this.basicAuditTime = basicAuditTime;
		this.provincialPanelAuditOpinion = provincialPanelAuditOpinion;
		this.provincialPanelSign = provincialPanelSign;
		this.provincialAuditTime = provincialAuditTime;
		this.meteDataSources = meteDataSources;
		this.meteLongitudeLatitude = meteLongitudeLatitude;
		this.meteIndicators = meteIndicators;
		this.meteIndicatorsReason = meteIndicatorsReason;
		this.state = state;
		this.remark = remark;
		this.produceBase = produceBase;
		this.stationLatitude = stationLatitude;
		this.climateStationName = climateStationName;
		this.startCollectionTime = startCollectionTime;
		this.endCollectionTime = endCollectionTime;
	}

	public String getQualityIdentificationNum() {
		return this.qualityIdentificationNum;
	}

	public void setQualityIdentificationNum(String qualityIdentificationNum) {
		this.qualityIdentificationNum = qualityIdentificationNum;
	}

	public String getApplyBh() {
		return this.applyBh;
	}

	public void setApplyBh(String applyBh) {
		this.applyBh = applyBh;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	public String getExpertsNum() {
		return this.expertsNum;
	}

	public void setExpertsNum(String expertsNum) {
		this.expertsNum = expertsNum;
	}

	public String getApplyFrequency() {
		return this.applyFrequency;
	}

	public void setApplyFrequency(String applyFrequency) {
		this.applyFrequency = applyFrequency;
	}

	public String getIdentificationer() {
		return this.identificationer;
	}

	public void setIdentificationer(String identificationer) {
		this.identificationer = identificationer;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getCropGrowthPeriod() {
		return this.cropGrowthPeriod;
	}

	public void setCropGrowthPeriod(String cropGrowthPeriod) {
		this.cropGrowthPeriod = cropGrowthPeriod;
	}

	public String getOriginSituation() {
		return this.originSituation;
	}

	public void setOriginSituation(String originSituation) {
		this.originSituation = originSituation;
	}

	public String getMeteorologicalDisaster() {
		return this.meteorologicalDisaster;
	}

	public void setMeteorologicalDisaster(String meteorologicalDisaster) {
		this.meteorologicalDisaster = meteorologicalDisaster;
	}

	public String getDiseasesInsectPests() {
		return this.diseasesInsectPests;
	}

	public void setDiseasesInsectPests(String diseasesInsectPests) {
		this.diseasesInsectPests = diseasesInsectPests;
	}

	public String getBasicPanelAuditOpinion() {
		return this.basicPanelAuditOpinion;
	}

	public void setBasicPanelAuditOpinion(String basicPanelAuditOpinion) {
		this.basicPanelAuditOpinion = basicPanelAuditOpinion;
	}

	public String getBasicPanelSign() {
		return this.basicPanelSign;
	}

	public void setBasicPanelSign(String basicPanelSign) {
		this.basicPanelSign = basicPanelSign;
	}

	public Date getBasicAuditTime() {
		return this.basicAuditTime;
	}

	public void setBasicAuditTime(Date basicAuditTime) {
		this.basicAuditTime = basicAuditTime;
	}

	public String getProvincialPanelAuditOpinion() {
		return this.provincialPanelAuditOpinion;
	}

	public void setProvincialPanelAuditOpinion(
			String provincialPanelAuditOpinion) {
		this.provincialPanelAuditOpinion = provincialPanelAuditOpinion;
	}

	public String getProvincialPanelSign() {
		return this.provincialPanelSign;
	}

	public void setProvincialPanelSign(String provincialPanelSign) {
		this.provincialPanelSign = provincialPanelSign;
	}

	public Date getProvincialAuditTime() {
		return this.provincialAuditTime;
	}

	public void setProvincialAuditTime(Date provincialAuditTime) {
		this.provincialAuditTime = provincialAuditTime;
	}

	public String getMeteDataSources() {
		return this.meteDataSources;
	}

	public void setMeteDataSources(String meteDataSources) {
		this.meteDataSources = meteDataSources;
	}

	public String getMeteLongitudeLatitude() {
		return this.meteLongitudeLatitude;
	}

	public void setMeteLongitudeLatitude(String meteLongitudeLatitude) {
		this.meteLongitudeLatitude = meteLongitudeLatitude;
	}

	public String getMeteIndicators() {
		return this.meteIndicators;
	}

	public void setMeteIndicators(String meteIndicators) {
		this.meteIndicators = meteIndicators;
	}

	public String getMeteIndicatorsReason() {
		return this.meteIndicatorsReason;
	}

	public void setMeteIndicatorsReason(String meteIndicatorsReason) {
		this.meteIndicatorsReason = meteIndicatorsReason;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getProduceBase() {
		return this.produceBase;
	}

	public void setProduceBase(String produceBase) {
		this.produceBase = produceBase;
	}

	public String getStationLatitude() {
		return this.stationLatitude;
	}

	public void setStationLatitude(String stationLatitude) {
		this.stationLatitude = stationLatitude;
	}

	public String getClimateStationName() {
		return this.climateStationName;
	}

	public void setClimateStationName(String climateStationName) {
		this.climateStationName = climateStationName;
	}

	public Date getStartCollectionTime() {
		return this.startCollectionTime;
	}

	public void setStartCollectionTime(Date startCollectionTime) {
		this.startCollectionTime = startCollectionTime;
	}

	public Date getEndCollectionTime() {
		return this.endCollectionTime;
	}

	public void setEndCollectionTime(Date endCollectionTime) {
		this.endCollectionTime = endCollectionTime;
	}

}
