package edu.cuit.module.label.entity;

// Generated 2015-4-14 20:41:11 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Labelscanrecord generated by hbm2java
 */
public class Labelscanrecord implements java.io.Serializable {

	private String scanRecordId;
	private String labelId;
	private String scanId;
	private Date scanTime;
	private String scanPlace;
	private String province;
	private String city;
	private String county;
	private String labelApplyBh;
	private String originID;

	public Labelscanrecord() {
	}

	public Labelscanrecord(String scanRecordId) {
		this.scanRecordId = scanRecordId;
	}

	public Labelscanrecord(String scanRecordId, String labelId, String scanId,
			Date scanTime, String scanPlace, String province, String city,
			String county) {
		this.scanRecordId = scanRecordId;
		this.labelId = labelId;
		this.scanId = scanId;
		this.scanTime = scanTime;
		this.scanPlace = scanPlace;
		this.province = province;
		this.city = city;
		this.county = county;
	}

	public String getScanRecordId() {
		return this.scanRecordId;
	}

	public void setScanRecordId(String scanRecordId) {
		this.scanRecordId = scanRecordId;
	}

	public String getLabelId() {
		return this.labelId;
	}

	public void setLabelId(String labelId) {
		this.labelId = labelId;
	}

	public String getScanId() {
		return this.scanId;
	}

	public void setScanId(String scanId) {
		this.scanId = scanId;
	}

	public Date getScanTime() {
		return this.scanTime;
	}

	public void setScanTime(Date scanTime) {
		this.scanTime = scanTime;
	}

	public String getScanPlace() {
		return this.scanPlace;
	}

	public void setScanPlace(String scanPlace) {
		this.scanPlace = scanPlace;
	}

	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getCounty() {
		return this.county;
	}

	public void setCounty(String county) {
		this.county = county;
	}

	public String getLabelApplyBh() {
		return labelApplyBh;
	}

	public void setLabelApplyBh(String labelApplyBh) {
		this.labelApplyBh = labelApplyBh;
	}

	public String getOriginID() {
		return originID;
	}

	public void setOriginID(String originID) {
		this.originID = originID;
	}
		
	
}
