package edu.cuit.module.auchc.entity;

// Generated 2015-4-14 19:14:43 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Apply generated by hbm2java
 */
public class Apply implements java.io.Serializable {

	private String applyBh;
	private String repersentative;
	private String unitProperty;
	private String counterMan;
	private String applicationType;
	private String honour;
	private String relationContact;
	private String countermanPhone;
	private String countermanFax;
	private String location;
	private String applyOriginType;
	private String produceBase;
	private String address;
	private String productionCharger;
	private Date applyTime;
	private String contact;
	private String phone;
	private String fax;
	private String email;
	private String isApplyOriginCode;
	private String productName;
	private String productBrand;
	private String productDescription;
	private String productOverview;
	private String produtOutput;
	private String outputValue;
	private String scale;
	private String regionManageOpinion;
	private String regionHeader;
	private Date regionAuditTime;
	private String cityManageAudit;
	private String cityHeader;
	private Date cityAuditTime;
	private String provinceManageOpinion;
	private String provinceHeader;
	private Date provinceAuditTime;
	private String controlImplement;
	private Integer number;
	private String format;
	private String applyPerson;
	private String declareStatus;
	private String declareStatusDescript;
	private String handleResult;
	private String handleDescription;
	private String inTotal;
	private String remark;
	private String isWithDraw;
	private String unityName;
	private String commodityType;
	private String establishedPlan;
	private String productScoreStatus;
	public Apply() {
	}

	public Apply(String applyBh) {
		this.applyBh = applyBh;
	}

	public Apply(String applyBh, String repersentative, String unitProperty,
			String counterMan, String applicationType, String honour,
			String relationContact, String countermanPhone,
			String countermanFax, String location, String applyOriginType,
			String produceBase, String address, String productionCharger,
			Date applyTime, String contact, String phone, String fax,
			String email, String isApplyOriginCode, String productName,
			String productBrand, String productDescription,
			String productOverview, String produtOutput, String outputValue,
			String scale, String regionManageOpinion, String regionHeader,
			Date regionAuditTime, String cityManageAudit, String cityHeader,
			Date cityAuditTime, String provinceManageOpinion,
			String provinceHeader, Date provinceAuditTime,
			String controlImplement, Integer number, String format,
			String applyPerson, String declareStatus, String handleResult,
			String handleDescription, String inTotal, String remark,
			String isWithDraw, String unityName, String commodityType) {
		this.applyBh = applyBh;
		this.repersentative = repersentative;
		this.unitProperty = unitProperty;
		this.counterMan = counterMan;
		this.applicationType = applicationType;
		this.honour = honour;
		this.relationContact = relationContact;
		this.countermanPhone = countermanPhone;
		this.countermanFax = countermanFax;
		this.location = location;
		this.applyOriginType = applyOriginType;
		this.produceBase = produceBase;
		this.address = address;
		this.productionCharger = productionCharger;
		this.applyTime = applyTime;
		this.contact = contact;
		this.phone = phone;
		this.fax = fax;
		this.email = email;
		this.isApplyOriginCode = isApplyOriginCode;
		this.productName = productName;
		this.productBrand = productBrand;
		this.productDescription = productDescription;
		this.productOverview = productOverview;
		this.produtOutput = produtOutput;
		this.outputValue = outputValue;
		this.scale = scale;
		this.regionManageOpinion = regionManageOpinion;
		this.regionHeader = regionHeader;
		this.regionAuditTime = regionAuditTime;
		this.cityManageAudit = cityManageAudit;
		this.cityHeader = cityHeader;
		this.cityAuditTime = cityAuditTime;
		this.provinceManageOpinion = provinceManageOpinion;
		this.provinceHeader = provinceHeader;
		this.provinceAuditTime = provinceAuditTime;
		this.controlImplement = controlImplement;
		this.number = number;
		this.format = format;
		this.applyPerson = applyPerson;
		this.declareStatus = declareStatus;
		this.handleResult = handleResult;
		this.handleDescription = handleDescription;
		this.inTotal = inTotal;
		this.remark = remark;
		this.isWithDraw = isWithDraw;
		this.unityName = unityName;
		this.commodityType = commodityType;
	}

	public String getApplyBh() {
		return this.applyBh;
	}

	public void setApplyBh(String applyBh) {
		this.applyBh = applyBh;
	}

	public String getRepersentative() {
		return this.repersentative;
	}

	public void setRepersentative(String repersentative) {
		this.repersentative = repersentative;
	}

	public String getUnitProperty() {
		return this.unitProperty;
	}

	public void setUnitProperty(String unitProperty) {
		this.unitProperty = unitProperty;
	}

	public String getCounterMan() {
		return this.counterMan;
	}

	public void setCounterMan(String counterMan) {
		this.counterMan = counterMan;
	}

	public String getApplicationType() {
		return this.applicationType;
	}

	public void setApplicationType(String applicationType) {
		this.applicationType = applicationType;
	}

	public String getHonour() {
		return this.honour;
	}

	public void setHonour(String honour) {
		this.honour = honour;
	}

	public String getRelationContact() {
		return this.relationContact;
	}

	public void setRelationContact(String relationContact) {
		this.relationContact = relationContact;
	}

	public String getCountermanPhone() {
		return this.countermanPhone;
	}

	public void setCountermanPhone(String countermanPhone) {
		this.countermanPhone = countermanPhone;
	}

	public String getCountermanFax() {
		return this.countermanFax;
	}

	public void setCountermanFax(String countermanFax) {
		this.countermanFax = countermanFax;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public String getApplyOriginType() {
		return this.applyOriginType;
	}

	public void setApplyOriginType(String applyOriginType) {
		this.applyOriginType = applyOriginType;
	}

	public String getProduceBase() {
		return this.produceBase;
	}

	public void setProduceBase(String produceBase) {
		this.produceBase = produceBase;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getProductionCharger() {
		return this.productionCharger;
	}

	public void setProductionCharger(String productionCharger) {
		this.productionCharger = productionCharger;
	}

	public Date getApplyTime() {
		return this.applyTime;
	}

	public void setApplyTime(Date applyTime) {
		this.applyTime = applyTime;
	}

	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getIsApplyOriginCode() {
		return this.isApplyOriginCode;
	}

	public void setIsApplyOriginCode(String isApplyOriginCode) {
		this.isApplyOriginCode = isApplyOriginCode;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public String getProductBrand() {
		return this.productBrand;
	}

	public void setProductBrand(String productBrand) {
		this.productBrand = productBrand;
	}

	public String getProductDescription() {
		return this.productDescription;
	}

	public void setProductDescription(String productDescription) {
		this.productDescription = productDescription;
	}

	public String getProductOverview() {
		return this.productOverview;
	}

	public void setProductOverview(String productOverview) {
		this.productOverview = productOverview;
	}

	public String getProdutOutput() {
		return this.produtOutput;
	}

	public void setProdutOutput(String produtOutput) {
		this.produtOutput = produtOutput;
	}

	public String getOutputValue() {
		return this.outputValue;
	}

	public void setOutputValue(String outputValue) {
		this.outputValue = outputValue;
	}

	public String getScale() {
		return this.scale;
	}

	public void setScale(String scale) {
		this.scale = scale;
	}

	public String getRegionManageOpinion() {
		return this.regionManageOpinion;
	}

	public void setRegionManageOpinion(String regionManageOpinion) {
		this.regionManageOpinion = regionManageOpinion;
	}

	public String getRegionHeader() {
		return this.regionHeader;
	}

	public void setRegionHeader(String regionHeader) {
		this.regionHeader = regionHeader;
	}

	public Date getRegionAuditTime() {
		return this.regionAuditTime;
	}

	public void setRegionAuditTime(Date regionAuditTime) {
		this.regionAuditTime = regionAuditTime;
	}

	public String getCityManageAudit() {
		return this.cityManageAudit;
	}

	public void setCityManageAudit(String cityManageAudit) {
		this.cityManageAudit = cityManageAudit;
	}

	public String getCityHeader() {
		return this.cityHeader;
	}

	public void setCityHeader(String cityHeader) {
		this.cityHeader = cityHeader;
	}

	public Date getCityAuditTime() {
		return this.cityAuditTime;
	}

	public void setCityAuditTime(Date cityAuditTime) {
		this.cityAuditTime = cityAuditTime;
	}

	public String getProvinceManageOpinion() {
		return this.provinceManageOpinion;
	}

	public void setProvinceManageOpinion(String provinceManageOpinion) {
		this.provinceManageOpinion = provinceManageOpinion;
	}

	public String getProvinceHeader() {
		return this.provinceHeader;
	}

	public void setProvinceHeader(String provinceHeader) {
		this.provinceHeader = provinceHeader;
	}

	public Date getProvinceAuditTime() {
		return this.provinceAuditTime;
	}

	public void setProvinceAuditTime(Date provinceAuditTime) {
		this.provinceAuditTime = provinceAuditTime;
	}

	public String getControlImplement() {
		return this.controlImplement;
	}

	public void setControlImplement(String controlImplement) {
		this.controlImplement = controlImplement;
	}

	public Integer getNumber() {
		return this.number;
	}

	public void setNumber(Integer number) {
		this.number = number;
	}

	public String getFormat() {
		return this.format;
	}

	public void setFormat(String format) {
		this.format = format;
	}

	public String getApplyPerson() {
		return this.applyPerson;
	}

	public void setApplyPerson(String applyPerson) {
		this.applyPerson = applyPerson;
	}

	public String getDeclareStatus() {
		return this.declareStatus;
	}
	public String getDeclareStatusDescript() {
		return this.declareStatusDescript;
	}

	public void setDeclareStatus(String declareStatus) {
		this.declareStatus = declareStatus;
	}
	
	public void setDesalareStatusDescript(String declareStatusDescript){
		this.declareStatusDescript = declareStatusDescript;
	}
	
	public String getHandleResult() {
		return this.handleResult;
	}

	public void setHandleResult(String handleResult) {
		this.handleResult = handleResult;
	}

	public String getHandleDescription() {
		return this.handleDescription;
	}

	public void setHandleDescription(String handleDescription) {
		this.handleDescription = handleDescription;
	}

	public String getInTotal() {
		return this.inTotal;
	}

	public void setInTotal(String inTotal) {
		this.inTotal = inTotal;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getIsWithDraw() {
		return this.isWithDraw;
	}

	public void setIsWithDraw(String isWithDraw) {
		this.isWithDraw = isWithDraw;
	}

	public String getUnityName() {
		return this.unityName;
	}

	public void setUnityName(String unityName) {
		this.unityName = unityName;
	}

	public String getCommodityType() {
		return this.commodityType;
	}

	public void setCommodityType(String commodityType) {
		this.commodityType = commodityType;
	}

	public String getEstablishedPlan() {
		return establishedPlan;
	}

	public void setEstablishedPlan(String establishedPlan) {
		this.establishedPlan = establishedPlan;
	}

	/**
	 * @return the productScoreStatus
	 */
	public String getProductScoreStatus() {
		return productScoreStatus;
	}

	/**
	 * @param productScoreStatus the productScoreStatus to set
	 */
	public void setProductScoreStatus(String productScoreStatus) {
		this.productScoreStatus = productScoreStatus;
	}

	/**
	 * @param declareStatusDescript the declareStatusDescript to set
	 */
	public void setDeclareStatusDescript(String declareStatusDescript) {
		this.declareStatusDescript = declareStatusDescript;
	}

}
